using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Turbo.Database.Context;

#nullable disable

namespace Turbo.Database.Migrations
{
    /// <summary>
    /// Rewrites what <c>MapCrackableFurni</c> set for every crackable furni in Sulake's furni data,
    /// now from that data alone (it replaces the whole <c>crackable</c> section, so it is the same
    /// whether or not the first one ran): its state count, its usage (<c>&lt;everyone-can-use/&gt;</c> makes it everyone's, as
    /// on eggs, crystals, piñatas and some plants; otherwise room rights, Habbo's default), whether it
    /// is walked on (<c>&lt;stand/&gt;</c>), and a <c>crackable</c> section in the definition's extra
    /// data built from its product parameter (reward set, target, required effect, hit
    /// achievements) and its server class:
    /// <list type="bullet">
    /// <item><c>PinataFurniture</c> is hit by walking under it wearing the piñata stick (effect 158):
    /// "use the Rainbow Piñata Stick effect and walk underneath it 100 times", the hotel's
    /// <c>catalog.page.pinatas.text_0</c>;</item>
    /// <item><c>PublicCrackableProductRewardFurniture</c> gives what it holds to whoever cracks it,
    /// the others to the furni's owner;</item>
    /// <item><c>CrackableInventoryProductRewardFurniture</c> puts its reward in the inventory, the
    /// others on the crackable's tile.</item>
    /// </list>
    /// What each holds is not in Sulake's data. The Habbo Club and Builders Club boxes hold 14 or 31
    /// days of their membership; 73 others hold what the Habbox Wiki lists for them, with its odds
    /// where it gives them and equal chances where it does not (a bonus bag: its six rares, 5 credits
    /// or 3 days of Habbo Club, "about a 1 in 8 chance of a certain colored rare"). The rest take hits
    /// but are not cracked until a hotel lists their <c>rewards</c>. A definition this hotel does
    /// not have is left alone. Data only: the model is unchanged, so there is no designer snapshot.
    /// </summary>
    [DbContext(typeof(TurboDbContext))]
    [Migration("20261008190000_RefineCrackableFurni")]
    public partial class RefineCrackableFurni : Migration
    {
        private const string LOGIC = "crackable";

        /// <summary>
        /// Name, the asset's state count, the usage policy (2 everyone, 1 room rights), whether it
        /// is walked on (<c>&lt;stand/&gt;</c>), the <c>crackable</c> section.
        /// </summary>
        private static readonly (
            string Name,
            int States,
            int Usage,
            bool Walkable,
            string Crackable
        )[] CRACKABLES =
        [
            (
                "bc_gift_14days",
                3,
                1,
                false,
                """{"rewardSet":"bcgift_1","target":1,"rewards":[{"subscription":"BuildersClub","subscriptionDays":14}]}"""
            ),
            (
                "bc_gift_31days",
                3,
                1,
                false,
                """{"rewardSet":"bcgift_2","target":1,"rewards":[{"subscription":"BuildersClub","subscriptionDays":31}]}"""
            ),
            (
                "bonusbag16_1",
                3,
                1,
                false,
                """{"rewardSet":"bonusrares16_1","target":1,"rewards":[{"furni":"bonusrare16_5*1"},{"furni":"bonusrare16_5*4"},{"furni":"bonusrare16_5*2"},{"furni":"bonusrare16_5*6"},{"furni":"bonusrare16_5*3"},{"furni":"bonusrare16_5*5"},{"credits":5},{"subscription":"HabboClub","subscriptionDays":3}]}"""
            ),
            (
                "bonusbag16_2",
                3,
                1,
                false,
                """{"rewardSet":"bonusrares16_2","target":1,"rewards":[{"furni":"bonusrare16_6*1"},{"furni":"bonusrare16_6*2"},{"furni":"bonusrare16_6*3"},{"furni":"bonusrare16_6*4"},{"furni":"bonusrare16_6*5"},{"furni":"bonusrare16_6*6"},{"credits":5},{"subscription":"HabboClub","subscriptionDays":3}]}"""
            ),
            (
                "bonusbag16_3",
                3,
                1,
                false,
                """{"rewardSet":"bonusrares16_3","target":1,"rewards":[{"furni":"bonusrare16_7*5"},{"furni":"bonusrare16_7*2"},{"furni":"bonusrare16_7*6"},{"furni":"bonusrare16_7*4"},{"furni":"bonusrare16_7*3"},{"furni":"bonusrare16_7*1"},{"credits":5},{"subscription":"HabboClub","subscriptionDays":3}]}"""
            ),
            (
                "bonusbag17_1",
                3,
                1,
                false,
                """{"rewardSet":"bonusrares17_1","target":1,"rewards":[{"furni":"bonusrare17_1*0"},{"furni":"bonusrare17_1*1"},{"furni":"bonusrare17_1*3"},{"furni":"bonusrare17_1*4"},{"furni":"bonusrare17_1*5"},{"furni":"bonusrare17_1*2"},{"credits":5},{"subscription":"HabboClub","subscriptionDays":3}]}"""
            ),
            (
                "bonusbag17_2",
                3,
                1,
                false,
                """{"rewardSet":"bonusrares17_2","target":1,"rewards":[{"furni":"bonusrare17_2*4"},{"furni":"bonusrare17_2*5"},{"furni":"bonusrare17_2*0"},{"furni":"bonusrare17_2*3"},{"furni":"bonusrare17_2*2"},{"furni":"bonusrare17_2*1"},{"credits":5},{"subscription":"HabboClub","subscriptionDays":3}]}"""
            ),
            (
                "bonusbag17_3",
                3,
                1,
                false,
                """{"rewardSet":"bonusrares17_3","target":1,"rewards":[{"furni":"bonusrare17_3*4"},{"furni":"bonusrare17_3*3"},{"furni":"bonusrare17_3*6"},{"furni":"bonusrare17_3*2"},{"furni":"bonusrare17_3*1"},{"furni":"bonusrare17_3*5"},{"credits":5},{"subscription":"HabboClub","subscriptionDays":3}]}"""
            ),
            (
                "bonusbag17_4",
                3,
                1,
                false,
                """{"rewardSet":"bonusrares17_4","target":1,"rewards":[{"furni":"bonusrare17_4*3"},{"furni":"bonusrare17_4*6"},{"furni":"bonusrare17_4*5"},{"furni":"bonusrare17_4*4"},{"furni":"bonusrare17_4*1"},{"furni":"bonusrare17_4*2"},{"credits":5},{"subscription":"HabboClub","subscriptionDays":3}]}"""
            ),
            (
                "bonusbag18_1",
                3,
                1,
                false,
                """{"rewardSet":"bonusrare18_1","target":1,"rewards":[{"furni":"bonusrare18_1*4"},{"furni":"bonusrare18_1*0"},{"furni":"bonusrare18_1*5"},{"furni":"bonusrare18_1*1"},{"furni":"bonusrare18_1*3"},{"furni":"bonusrare18_1*2"},{"credits":5},{"subscription":"HabboClub","subscriptionDays":3}]}"""
            ),
            (
                "bonusbag18_2",
                3,
                1,
                false,
                """{"rewardSet":"bonusrare18_2","target":1,"rewards":[{"furni":"bonusrare18_2*3"},{"furni":"bonusrare18_2*2"},{"furni":"bonusrare18_2*5"},{"furni":"bonusrare18_2*4"},{"furni":"bonusrare18_2*1"},{"furni":"bonusrare18_2*0"},{"credits":5},{"subscription":"HabboClub","subscriptionDays":3}]}"""
            ),
            (
                "bonusbag18_3",
                3,
                1,
                false,
                """{"rewardSet":"bonusrare18_3","target":1,"rewards":[{"furni":"bonusrare18_3*4"},{"furni":"bonusrare18_3*3"},{"furni":"bonusrare18_3*2"},{"furni":"bonusrare18_3*1"},{"furni":"bonusrare18_3*0"},{"furni":"bonusrare18_3*5"},{"credits":5},{"subscription":"HabboClub","subscriptionDays":3}]}"""
            ),
            (
                "bonusbag18_4",
                3,
                1,
                false,
                """{"rewardSet":"bonusrare18_4","target":1,"rewards":[{"furni":"bonusrare18_4*1"},{"furni":"bonusrare18_4*4"},{"furni":"bonusrare18_4*0"},{"furni":"bonusrare18_4*3"},{"furni":"bonusrare18_4*5"},{"furni":"bonusrare18_4*2"},{"credits":5},{"subscription":"HabboClub","subscriptionDays":3}]}"""
            ),
            (
                "bonusbag19_1",
                3,
                1,
                false,
                """{"rewardSet":"bonusrare19_1","target":1,"rewards":[{"furni":"bonusrare19_1*0"},{"furni":"bonusrare19_1*1"},{"furni":"bonusrare19_1*2"},{"furni":"bonusrare19_1*3"},{"furni":"bonusrare19_1*4"},{"furni":"bonusrare19_1*5"},{"credits":5},{"subscription":"HabboClub","subscriptionDays":3}]}"""
            ),
            (
                "bonusbag19_2",
                3,
                1,
                false,
                """{"rewardSet":"bonusrare19_2","target":1,"rewards":[{"furni":"bonusrare19_2*0"},{"furni":"bonusrare19_2*1"},{"furni":"bonusrare19_2*2"},{"furni":"bonusrare19_2*3"},{"furni":"bonusrare19_2*4"},{"furni":"bonusrare19_2*5"},{"credits":5},{"subscription":"HabboClub","subscriptionDays":3}]}"""
            ),
            (
                "bonusbag19_3",
                3,
                1,
                false,
                """{"rewardSet":"bonusrare19_3","target":1,"rewards":[{"furni":"bonusrare19_3*0"},{"furni":"bonusrare19_3*1"},{"furni":"bonusrare19_3*2"},{"furni":"bonusrare19_3*3"},{"furni":"bonusrare19_3*4"},{"furni":"bonusrare19_3*5"},{"credits":5},{"subscription":"HabboClub","subscriptionDays":3}]}"""
            ),
            (
                "bonusbag19_4",
                3,
                1,
                false,
                """{"rewardSet":"bonusrare19_4","target":1,"rewards":[{"furni":"bonusrare19_4*0"},{"furni":"bonusrare19_4*1"},{"furni":"bonusrare19_4*2"},{"furni":"bonusrare19_4*3"},{"furni":"bonusrare19_4*4"},{"furni":"bonusrare19_4*5"},{"credits":5},{"subscription":"HabboClub","subscriptionDays":3}]}"""
            ),
            (
                "bonusbag20_1",
                3,
                1,
                false,
                """{"rewardSet":"bonusrares20_1","target":1,"rewards":[{"furni":"bonusrare20_1a*1"},{"furni":"bonusrare20_1a*2"},{"furni":"bonusrare20_1a*3"},{"furni":"bonusrare20_1a*4"},{"furni":"bonusrare20_1a*5"},{"furni":"bonusrare20_1a*6"},{"credits":5},{"subscription":"HabboClub","subscriptionDays":3}]}"""
            ),
            (
                "bonusbag20_2",
                3,
                1,
                false,
                """{"rewardSet":"bonusrares20_2","target":1,"rewards":[{"furni":"bonusrare20_2*1"},{"furni":"bonusrare20_2*2"},{"furni":"bonusrare20_2*3"},{"furni":"bonusrare20_2*4"},{"furni":"bonusrare20_2*5"},{"furni":"bonusrare20_2*6"},{"credits":5},{"subscription":"HabboClub","subscriptionDays":3}]}"""
            ),
            (
                "bonusbag20_3",
                3,
                1,
                false,
                """{"rewardSet":"bonusrares20_3","target":1,"rewards":[{"furni":"bonusrare20_3*1"},{"furni":"bonusrare20_3*2"},{"furni":"bonusrare20_3*3"},{"furni":"bonusrare20_3*4"},{"furni":"bonusrare20_3*5"},{"furni":"bonusrare20_3*6"},{"credits":5},{"subscription":"HabboClub","subscriptionDays":3}]}"""
            ),
            (
                "bonusbag20_4",
                3,
                1,
                false,
                """{"rewardSet":"bonusrares20_4","target":1,"rewards":[{"furni":"bonusrare20_4*0"},{"furni":"bonusrare20_4*1"},{"furni":"bonusrare20_4*2"},{"furni":"bonusrare20_4*3"},{"furni":"bonusrare20_4*4"},{"furni":"bonusrare20_4*5"},{"credits":5},{"subscription":"HabboClub","subscriptionDays":3}]}"""
            ),
            (
                "bonusbag21_1",
                3,
                1,
                false,
                """{"rewardSet":"bonusrares21_1","target":1,"rewards":[{"furni":"bonusrare21_1a*0"},{"furni":"bonusrare21_1a*1"},{"furni":"bonusrare21_1a*2"},{"furni":"bonusrare21_1a*3"},{"furni":"bonusrare21_1a*4"},{"furni":"bonusrare21_1a*5"},{"credits":5},{"subscription":"HabboClub","subscriptionDays":3}]}"""
            ),
            (
                "bonusbag21_2",
                3,
                1,
                false,
                """{"rewardSet":"bonusrares21_2","target":1,"rewards":[{"furni":"bonusrare21_2*0"},{"furni":"bonusrare21_2*1"},{"furni":"bonusrare21_2*2"},{"furni":"bonusrare21_2*3"},{"furni":"bonusrare21_2*4"},{"furni":"bonusrare21_2*5"},{"credits":5},{"subscription":"HabboClub","subscriptionDays":3}]}"""
            ),
            (
                "bonusbag21_3",
                3,
                1,
                false,
                """{"rewardSet":"bonusrares21_3","target":1,"rewards":[{"furni":"bonusrare21_3*1"},{"furni":"bonusrare21_3*2"},{"furni":"bonusrare21_3*3"},{"furni":"bonusrare21_3*4"},{"furni":"bonusrare21_3*5"},{"furni":"bonusrare21_3*6"},{"credits":5},{"subscription":"HabboClub","subscriptionDays":3}]}"""
            ),
            (
                "bonusbag21_4",
                3,
                1,
                false,
                """{"rewardSet":"bonusrares21_4","target":1,"rewards":[{"furni":"bonusrare21_4*0"},{"furni":"bonusrare21_4*1"},{"furni":"bonusrare21_4*2"},{"furni":"bonusrare21_4*3"},{"furni":"bonusrare21_4*4"},{"furni":"bonusrare21_4*5"},{"credits":5},{"subscription":"HabboClub","subscriptionDays":3}]}"""
            ),
            (
                "booster_c19_box1",
                3,
                1,
                false,
                """{"rewardSet":"booster19_1_blue","target":1,"rewardPlacement":"Inventory"}"""
            ),
            (
                "booster_c19_box2",
                3,
                1,
                false,
                """{"rewardSet":"booster19_1_red","target":1,"rewardPlacement":"Inventory"}"""
            ),
            (
                "booster_c20_box",
                3,
                1,
                false,
                """{"rewardSet":"booster20_1","target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"art_c20_clock","weight":1393},{"furni":"art_c20_pillow","weight":1393},{"furni":"art_c20_chair1","weight":1393},{"furni":"art_c20_chair2","weight":1393},{"furni":"art_c20_chair3","weight":1393},{"furni":"art_c20_chair4","weight":1393},{"furni":"clothing_c20_heartbackpack","weight":1393},{"furni":"art_c20_gold5","weight":42},{"furni":"art_c20_gold4","weight":42},{"furni":"art_c20_gold1","weight":42},{"furni":"art_c20_gold2","weight":42},{"furni":"art_c20_gold3","weight":42},{"furni":"clothing_c20_goldheartbp","weight":42}]}"""
            ),
            (
                "coralking_c18_treasurechest",
                3,
                1,
                false,
                """{"rewardSet":"coralking_1","target":1,"rewardPlacement":"Inventory"}"""
            ),
            (
                "coralking_r18_goldenchest",
                3,
                1,
                false,
                """{"rewardSet":"coralking_2","target":1,"rewardPlacement":"Inventory"}"""
            ),
            (
                "diamond_c18_giftbox",
                3,
                1,
                false,
                """{"rewardSet":"diamond18","target":1,"rewards":[{"furni":"clothing_diafish","weight":10},{"furni":"clothing_dianoblecrown","weight":20},{"furni":"clothing_luscioushair","weight":70},{"furni":"clothing_twotonecardi","weight":75},{"furni":"clothing_cjersey","weight":75},{"furni":"clothing_sliponcanvas","weight":75},{"furni":"clothing_hipsterglasses","weight":75},{"furni":"jungle_c16_roof","weight":90},{"furni":"attic15_paintingfloor","weight":90},{"furni":"bazaar_c17_bubblejuiceblower","weight":90},{"furni":"cpunk_c15_traffic","weight":90},{"furni":"paris_c15_flowerstl","weight":100}]}"""
            ),
            (
                "easter13_egg_0",
                15,
                2,
                false,
                """{"rewardSet":"egg_p1","target":1000,"incrementalHitAchievement":"EggCracker","finalHitAchievement":"EggMaster","rewards":[{"furni":"barchair_silo"},{"furni":"chair_silo"},{"furni":"divider_silo1"},{"furni":"divider_silo3"},{"furni":"safe_silo"},{"furni":"sofa_silo"},{"furni":"sofachair_silo"},{"furni":"table_silo_med"},{"furni":"table_silo_small"}]}"""
            ),
            (
                "easter13_egg_1",
                15,
                2,
                false,
                """{"rewardSet":"egg_p2","target":5000,"incrementalHitAchievement":"EggCracker","finalHitAchievement":"EggMaster","rewards":[{"furni":"penguin_frank"},{"furni":"penguin_skele"},{"furni":"penguin_tribal"},{"furni":"penguin_wip"}]}"""
            ),
            (
                "easter13_egg_2",
                15,
                2,
                false,
                """{"rewardSet":"egg_p3","target":10000,"incrementalHitAchievement":"EggCracker","finalHitAchievement":"EggMaster","rewards":[{"furni":"duck_zombie"},{"furni":"duck_scuba"},{"furni":"duck_frank"},{"furni":"duck_afro"}]}"""
            ),
            (
                "easter13_egg_3",
                15,
                2,
                false,
                """{"rewardSet":"egg_p4","target":20000,"incrementalHitAchievement":"EggCracker","finalHitAchievement":"EggMaster","rewards":[{"furni":"easter13_stonefrank"},{"furni":"easter13_stonehead"},{"furni":"easter13_sub"}]}"""
            ),
            (
                "easter_c17_egg",
                21,
                2,
                false,
                """{"rewardSet":"easter17_6","target":10,"rewardTo":"Cracker"}"""
            ),
            (
                "easter_c17_floweringbush",
                3,
                1,
                false,
                """{"rewardSet":"easter17_5","target":1,"requiredEffectId":192,"finalHitAchievement":"Farmer"}"""
            ),
            (
                "easter_c17_leafsprout",
                3,
                1,
                false,
                """{"rewardSet":"easter17_4","target":1,"requiredEffectId":192,"finalHitAchievement":"Farmer"}"""
            ),
            (
                "easter_c17_sapling",
                3,
                1,
                false,
                """{"rewardSet":"easter17_3","target":1,"requiredEffectId":192}"""
            ),
            ("easter_c17_seedbag", 3, 1, false, """{"rewardSet":"easter17_1","target":1}"""),
            (
                "easter_c17_seeds",
                3,
                1,
                false,
                """{"rewardSet":"easter17_2","target":1,"requiredEffectId":192}"""
            ),
            (
                "easter_c18_lupin1",
                13,
                1,
                true,
                """{"rewardSet":"easter18_3","target":12,"requiredEffectId":192,"finalHitAchievement":"AdvancedHorticulturist"}"""
            ),
            (
                "easter_c18_lupin2",
                13,
                1,
                true,
                """{"rewardSet":"easter18_3","target":12,"requiredEffectId":192,"finalHitAchievement":"AdvancedHorticulturist"}"""
            ),
            (
                "easter_c18_lupin3",
                13,
                1,
                true,
                """{"rewardSet":"easter18_3","target":12,"requiredEffectId":192,"finalHitAchievement":"AdvancedHorticulturist"}"""
            ),
            (
                "easter_c18_lupin4",
                13,
                1,
                true,
                """{"rewardSet":"easter18_3","target":12,"requiredEffectId":192,"finalHitAchievement":"AdvancedHorticulturist"}"""
            ),
            (
                "easter_c18_rose1",
                13,
                1,
                true,
                """{"rewardSet":"easter18_1","target":12,"requiredEffectId":192,"finalHitAchievement":"AdvancedHorticulturist"}"""
            ),
            (
                "easter_c18_rose2",
                13,
                1,
                true,
                """{"rewardSet":"easter18_1","target":12,"requiredEffectId":192,"finalHitAchievement":"AdvancedHorticulturist"}"""
            ),
            (
                "easter_c18_rose3",
                13,
                1,
                true,
                """{"rewardSet":"easter18_1","target":12,"requiredEffectId":192,"finalHitAchievement":"AdvancedHorticulturist"}"""
            ),
            (
                "easter_c18_rose4",
                13,
                1,
                true,
                """{"rewardSet":"easter18_1","target":12,"requiredEffectId":192,"finalHitAchievement":"AdvancedHorticulturist"}"""
            ),
            (
                "easter_c18_seedpacklupin",
                3,
                1,
                false,
                """{"rewardSet":"easter18_seed3","target":1}"""
            ),
            (
                "easter_c18_seedpackrose",
                3,
                1,
                false,
                """{"rewardSet":"easter18_seed1","target":1}"""
            ),
            (
                "easter_c18_seedpacksnowdrop",
                3,
                1,
                false,
                """{"rewardSet":"easter18_seed4","target":1}"""
            ),
            (
                "easter_c18_seedpacktulip",
                3,
                1,
                false,
                """{"rewardSet":"easter18_seed2","target":1}"""
            ),
            (
                "easter_c18_snowdrop1",
                13,
                1,
                true,
                """{"rewardSet":"easter18_4","target":12,"requiredEffectId":192,"finalHitAchievement":"AdvancedHorticulturist"}"""
            ),
            (
                "easter_c18_snowdrop2",
                13,
                1,
                true,
                """{"rewardSet":"easter18_4","target":12,"requiredEffectId":192,"finalHitAchievement":"AdvancedHorticulturist"}"""
            ),
            (
                "easter_c18_snowdrop3",
                13,
                1,
                true,
                """{"rewardSet":"easter18_4","target":12,"requiredEffectId":192,"finalHitAchievement":"AdvancedHorticulturist"}"""
            ),
            (
                "easter_c18_snowdrop4",
                13,
                1,
                true,
                """{"rewardSet":"easter18_4","target":12,"requiredEffectId":192,"finalHitAchievement":"AdvancedHorticulturist"}"""
            ),
            (
                "easter_c18_tulip1",
                13,
                1,
                true,
                """{"rewardSet":"easter18_2","target":12,"requiredEffectId":192,"finalHitAchievement":"AdvancedHorticulturist"}"""
            ),
            (
                "easter_c18_tulip2",
                13,
                1,
                true,
                """{"rewardSet":"easter18_2","target":12,"requiredEffectId":192,"finalHitAchievement":"AdvancedHorticulturist"}"""
            ),
            (
                "easter_c18_tulip3",
                13,
                1,
                true,
                """{"rewardSet":"easter18_2","target":12,"requiredEffectId":192,"finalHitAchievement":"AdvancedHorticulturist"}"""
            ),
            (
                "easter_c18_tulip4",
                13,
                1,
                true,
                """{"rewardSet":"easter18_2","target":12,"requiredEffectId":192,"finalHitAchievement":"AdvancedHorticulturist"}"""
            ),
            (
                "easter_c19_ancientbook",
                3,
                1,
                false,
                """{"rewardSet":"easter19_5","target":1,"requiredEffectId":186}"""
            ),
            (
                "easter_c19_babyent",
                25,
                1,
                false,
                """{"rewardSet":"easter19_3","target":12,"requiredEffectId":186,"finalHitAchievement":"EasterCreatures"}"""
            ),
            (
                "easter_c19_babyhippogriff",
                25,
                1,
                false,
                """{"rewardSet":"easter19_4","target":12,"requiredEffectId":186,"finalHitAchievement":"EasterCreatures"}"""
            ),
            (
                "easter_c19_babykelpie",
                25,
                1,
                false,
                """{"rewardSet":"easter19_2","target":12,"requiredEffectId":186,"finalHitAchievement":"EasterCreatures"}"""
            ),
            ("easter_c19_book1", 3, 1, false, """{"rewardSet":"easter19_6","target":1}"""),
            ("easter_c19_book2", 3, 1, false, """{"rewardSet":"easter19_7","target":1}"""),
            ("easter_c19_book3", 3, 1, false, """{"rewardSet":"easter19_8","target":1}"""),
            ("easter_c19_book4", 3, 1, false, """{"rewardSet":"easter19_9","target":1}"""),
            (
                "easter_c19_forrestegg",
                25,
                1,
                false,
                """{"rewardSet":"easter19_1","target":12,"requiredEffectId":186,"finalHitAchievement":"EasterCreatures"}"""
            ),
            (
                "easter_c20_darkprize1",
                3,
                1,
                false,
                """{"rewardSet":"easter20_dark1","target":1,"requiredEffectId":186,"rewards":[{"furni":"easter_c20_clayrelic"}]}"""
            ),
            (
                "easter_c20_darkprize2",
                3,
                1,
                false,
                """{"rewardSet":"easter20_dark2","target":1,"requiredEffectId":186,"rewards":[{"furni":"easter_c20_ancienthorse"}]}"""
            ),
            (
                "easter_c20_darkprize3",
                3,
                1,
                false,
                """{"rewardSet":"easter20_dark3","target":1,"requiredEffectId":186,"rewards":[{"furni":"easter_c20_zenmaster"}]}"""
            ),
            (
                "easter_c20_darkprize4",
                3,
                1,
                false,
                """{"rewardSet":"easter20_dark4","target":1,"requiredEffectId":186,"rewards":[{"furni":"clothing_mysticcrown"}]}"""
            ),
            (
                "easter_c20_darkrock",
                3,
                1,
                false,
                """{"rewardSet":"easter20_dark0","target":1,"requiredEffectId":183,"rewards":[{"furni":"easter_c20_darkprize1","weight":3125},{"furni":"easter_c20_darkprize2","weight":3125},{"furni":"easter_c20_darkprize3","weight":3125},{"furni":"easter_c20_darkprize4","weight":625}]}"""
            ),
            (
                "easter_c20_lightprize1",
                3,
                1,
                false,
                """{"rewardSet":"easter20_light1","target":1,"requiredEffectId":186,"rewards":[{"furni":"easter_c20_ancientbird"}]}"""
            ),
            (
                "easter_c20_lightprize2",
                3,
                1,
                false,
                """{"rewardSet":"easter20_light2","target":1,"requiredEffectId":186,"rewards":[{"furni":"easter_c20_jadeguardian"}]}"""
            ),
            (
                "easter_c20_lightprize3",
                3,
                1,
                false,
                """{"rewardSet":"easter20_light3","target":1,"requiredEffectId":186,"rewards":[{"furni":"easter_c20_ancientstatue"}]}"""
            ),
            (
                "easter_c20_lightprize4",
                3,
                1,
                false,
                """{"rewardSet":"easter20_light4","target":1,"requiredEffectId":186,"rewards":[{"furni":"clothing_mysticrobes"}]}"""
            ),
            (
                "easter_c20_lightrock",
                3,
                1,
                false,
                """{"rewardSet":"easter20_light0","target":1,"requiredEffectId":183,"rewards":[{"furni":"easter_c20_lightprize3","weight":3125},{"furni":"easter_c20_lightprize2","weight":3125},{"furni":"easter_c20_lightprize1","weight":3125},{"furni":"easter_c20_lightprize4","weight":625}]}"""
            ),
            (
                "easter_r16_crackable",
                3,
                1,
                false,
                """{"rewardSet":"easter16","target":1,"rewards":[{"furni":"gothic_r16_fountain"},{"furni":"easter_r16_gold"},{"furni":"easter_r16_squid"},{"furni":"easter_r16_pot"},{"furni":"easter_r16_throne"}]}"""
            ),
            ("fest_c19_bprintcrackable", 3, 1, false, """{"rewardSet":"fest19_1","target":1}"""),
            (
                "gold_rare_crackable",
                3,
                1,
                false,
                """{"rewardSet":"gold_1","target":1,"rewards":[{"furni":"gold_c15_arc_geysir"},{"furni":"gold_c15_arc_camp"},{"furni":"gold_c15_arc_chair"},{"furni":"gold_c15_arc_tree2"},{"furni":"gold_c15_arc_tree1"},{"furni":"gold_c15_arc_tub"},{"furni":"gold_c15_arc_lamp"},{"furni":"gold_c15_arc_statue"},{"furni":"gold_c15_arc_seat"},{"furni":"gold_c15_arc_table"}]}"""
            ),
            (
                "habbo15_crackable",
                1,
                1,
                false,
                """{"rewardSet":"habboanv_1","target":1,"incrementalHitAchievement":"PinataWhacker","finalHitAchievement":"PinataWhacker"}"""
            ),
            ("habbo15_pumpkin1", 3, 1, false, """{"rewardSet":"habbocalypse_1","target":1}"""),
            (
                "habbo15_pumpkin2",
                3,
                1,
                false,
                """{"rewardSet":"habbocalypse_2","target":1,"rewards":[{"furni":"duck_afro"},{"furni":"hween14_goat"},{"furni":"hween12_guillotine"},{"furni":"hween15_evilraider"},{"furni":"hween15_evilfrank"},{"furni":"hween15_saintta"},{"furni":"hween15_saintini"}]}"""
            ),
            (
                "habbo15_rare_crackable",
                1,
                1,
                false,
                """{"rewardSet":"habboanv_2","target":1,"incrementalHitAchievement":"PinataWhacker","finalHitAchievement":"PinataWhacker","rewards":[{"furni":"rare_beehive_bulb*3"},{"furni":"pillar*10"},{"furni":"rare_dragonlamp*10"},{"furni":"rare_elephant_statue*3"},{"furni":"rare_fountain*4"},{"furni":"rare_icecream*11"},{"furni":"scifiport*10"},{"furni":"marquee*11"},{"furni":"wooden_screen*10"},{"furni":"rare_parasol*4"},{"furni":"pillow*10"},{"furni":"rare_fan*10"},{"furni":"sleepingbag*11"},{"furni":"scifirocket*10"},{"furni":"scifidoor*11"}]}"""
            ),
            (
                "habbo20_c20_crackable",
                3,
                1,
                false,
                """{"rewardSet":"habbo20_common","target":1,"rewards":[{"furni":"habbo20_c20_crackable","weight":36},{"furni":"habbo20_r20_crackable","weight":4},{"furni":"clothing_meowtfit","weight":60},{"furni":"clothing_casualoutfit1","weight":100},{"furni":"clothing_demonoutfit","weight":100},{"furni":"clothing_mermaidoutfit","weight":100},{"furni":"clothing_messycurls","weight":120},{"furni":"clothing_knithat","weight":120},{"furni":"clothing_cyphones","weight":120},{"furni":"clothing_tux","weight":120},{"furni":"clothing_witchrobes","weight":120}]}"""
            ),
            (
                "habbo20_r20_crackable",
                3,
                1,
                false,
                """{"rewardSet":"habbo20_rare","target":1,"rewards":[{"furni":"rare_blackrosegold_dragonlamp"},{"furni":"rare_blackrosegold_icecream","weight":2},{"furni":"rare_blackrosegold_fountain","weight":4},{"furni":"rare_blackrosegold_elephant_statue","weight":4},{"furni":"rare_blackrosegold_parasol","weight":4},{"furni":"rare_blackrosegold_scifiport","weight":6},{"furni":"rare_blackrosegold_fan","weight":6},{"furni":"rare_blackrosegold_pillow","weight":6},{"furni":"rare_blackrosegold_scifidoor","weight":7},{"furni":"rare_blackrosegold_scifirocket","weight":7},{"furni":"rare_blackrosegold_beehive_bulb","weight":7},{"furni":"rare_blackrosegold_sleepingbag","weight":9},{"furni":"rare_blackrosegold_wooden_screen","weight":9},{"furni":"rare_blackrosegold_pillar","weight":9},{"furni":"rare_blackrosegold_marquee","weight":9},{"furni":"rare_blackrosegold_barrier","weight":10}]}"""
            ),
            (
                "hblooza14_pinata1",
                9,
                2,
                true,
                """{"rewardSet":"pinata1","target":100,"hitOn":"Walk","requiredEffectId":158,"incrementalHitAchievement":"PinataWhacker","finalHitAchievement":"PinataBreaker","rewards":[{"furni":"hblooza14_duck_balloon_y"},{"furni":"hblooza14_duck_balloon_b"},{"furni":"hblooza14_duck_balloon_p"}]}"""
            ),
            (
                "hblooza14_pinata2",
                9,
                2,
                true,
                """{"rewardSet":"pinata1","target":100,"hitOn":"Walk","requiredEffectId":158,"incrementalHitAchievement":"PinataWhacker","finalHitAchievement":"PinataBreaker","rewards":[{"furni":"hblooza14_cafe_y"},{"furni":"hblooza14_cafe_b"},{"furni":"hblooza14_cafe_p"}]}"""
            ),
            (
                "hblooza14_pinata3",
                9,
                2,
                true,
                """{"rewardSet":"pinata1","target":100,"hitOn":"Walk","requiredEffectId":158,"incrementalHitAchievement":"PinataWhacker","finalHitAchievement":"PinataBreaker","rewards":[{"furni":"hblooza14_horsecaroy"},{"furni":"hblooza14_horsecarob"},{"furni":"hblooza14_horsecarop"}]}"""
            ),
            (
                "hblooza14_pinata4",
                9,
                2,
                true,
                """{"rewardSet":"green_pinata","target":100,"hitOn":"Walk","requiredEffectId":158,"incrementalHitAchievement":"PinataWhacker","finalHitAchievement":"PinataBreaker","rewards":[{"furni":"hblooza14_hotair_y"},{"furni":"hblooza14_hotair_b"},{"furni":"hblooza14_hotair_p"}]}"""
            ),
            (
                "hblooza_pinata1",
                9,
                2,
                true,
                """{"rewardSet":"pinata1","target":100,"hitOn":"Walk","requiredEffectId":158,"incrementalHitAchievement":"pinatawhacker","finalHitAchievement":"pinatabreaker"}"""
            ),
            (
                "hblooza_pinata2",
                9,
                2,
                true,
                """{"rewardSet":"pinata2","target":100,"hitOn":"Walk","requiredEffectId":158,"incrementalHitAchievement":"pinatawhacker","finalHitAchievement":"pinatabreaker"}"""
            ),
            (
                "hc_gift_14days",
                3,
                1,
                false,
                """{"rewardSet":"hcgift_1","target":1,"rewards":[{"subscription":"HabboClub","subscriptionDays":14}]}"""
            ),
            (
                "hc_gift_31days",
                3,
                1,
                false,
                """{"rewardSet":"hcgift_2","target":1,"rewards":[{"subscription":"HabboClub","subscriptionDays":31}]}"""
            ),
            (
                "hhistory_r16_crackable",
                3,
                1,
                false,
                """{"rewardSet":"hhistory_16","target":1,"rewards":[{"furni":"rare_colourable_dragonlamp*1"},{"furni":"rare_colourable_pillow*1"},{"furni":"rare_colourable_icecream*1"},{"furni":"rare_colourable_elephant_statue*1"},{"furni":"rare_colourable_fountain*1"},{"furni":"rare_colourable_fan*1"},{"furni":"rare_colourable_beehive_bulb*1"},{"furni":"rare_colourable_scifiport*1"},{"furni":"rare_colourable_scifirocket*1"},{"furni":"rare_colourable_parasol*1"},{"furni":"rare_colourable_marquee*1"},{"furni":"rare_colourable_pillar*1"},{"furni":"rare_colourable_scifidoor*1"},{"furni":"rare_colourable_wooden_screen*1"},{"furni":"rare_colourable_barrier*1"}]}"""
            ),
            (
                "hhistory_r17_crackable",
                3,
                1,
                false,
                """{"rewardSet":"hhistory_17","target":1,"rewards":[{"furni":"rare_colourable_dragonlamp*2"},{"furni":"rare_colourable_pillow*2"},{"furni":"rare_colourable_icecream*2"},{"furni":"rare_colourable_elephant_statue*2"},{"furni":"rare_colourable_fountain*2"},{"furni":"rare_colourable_fan*2"},{"furni":"rare_colourable_beehive_bulb*2"},{"furni":"rare_colourable_scifiport*2"},{"furni":"rare_colourable_scifirocket*2"},{"furni":"rare_colourable_parasol*2"},{"furni":"rare_colourable_marquee*2"},{"furni":"rare_colourable_pillar*2"},{"furni":"rare_colourable_scifidoor*2"},{"furni":"rare_colourable_wooden_screen*2"},{"furni":"rare_colourable_sleepingbag*2"}]}"""
            ),
            (
                "hhistory_r18_crackable",
                3,
                1,
                false,
                """{"rewardSet":"hhistory_18","target":1,"rewards":[{"furni":"rare_colourable_dragonlamp*3"},{"furni":"rare_colourable_pillow*3"},{"furni":"rare_colourable_icecream*3"},{"furni":"rare_colourable_fountain*3"},{"furni":"rare_colourable_parasol*3"},{"furni":"rare_colourable_fan*3"},{"furni":"rare_colourable_elephant_statue*3"},{"furni":"rare_colourable_scifiport*3"},{"furni":"rare_colourable_pillar*3"},{"furni":"rare_colourable_scifidoor*3"},{"furni":"rare_colourable_scifirocket*3"},{"furni":"rare_colourable_wooden_screen*3"},{"furni":"rare_colourable_marquee*3"},{"furni":"rare_colourable_sleepingbag*3"},{"furni":"rare_colourable_beehive_bulb*3"},{"furni":"rare_colourable_barrier*3"}]}"""
            ),
            ("hween_c15_pumpkin1", 3, 1, false, """{"rewardSet":"habbocalypse_1","target":1}"""),
            (
                "hween_c15_pumpkin2",
                3,
                1,
                false,
                """{"rewardSet":"habbocalypse_2","target":1,"rewards":[{"furni":"duck_afro"},{"furni":"hween14_goat"},{"furni":"hween12_guillotine"},{"furni":"hween15_evilraider"},{"furni":"hween15_evilfrank"},{"furni":"hween15_saintta"},{"furni":"hween15_saintini"}]}"""
            ),
            (
                "hween_c16_crackable1",
                21,
                2,
                false,
                """{"rewardSet":"habboanv_1","target":10,"rewardTo":"Cracker"}"""
            ),
            (
                "hween_c17_flamingknight",
                21,
                1,
                false,
                """{"rewardSet":"hween17","target":10,"finalHitAchievement":"flamingknight"}"""
            ),
            (
                "hween_c19_witchsatchel",
                3,
                1,
                false,
                """{"rewardSet":"hween19_witchsatchel","target":1}"""
            ),
            (
                "hween_c20_duckgoddess",
                23,
                1,
                false,
                """{"rewardSet":"hween20_6","target":11,"requiredEffectId":186,"rewards":[{"furni":"hween_c20_goddessthrone","weight":45},{"furni":"hween_c20_goddesscrystal","weight":45},{"furni":"clothing_wingstiara","weight":10}]}"""
            ),
            (
                "hween_c20_evilscarecrow",
                23,
                1,
                false,
                """{"rewardSet":"hween20_5","target":11,"requiredEffectId":5,"rewards":[{"furni":"hween_c20_crookedtree","weight":45},{"furni":"hween_c20_crookedclock","weight":45},{"furni":"clothing_crookedhat","weight":10}]}"""
            ),
            (
                "hween_c20_eyedemon",
                23,
                1,
                false,
                """{"rewardSet":"hween20_4","target":11,"requiredEffectId":162,"rewards":[{"furni":"hween_c20_eyesofa","weight":45},{"furni":"hween_c20_eyetv","weight":45},{"furni":"clothing_multieyesface","weight":10}]}"""
            ),
            (
                "hween_c20_octodemon",
                23,
                1,
                false,
                """{"rewardSet":"hween20_3","target":11,"requiredEffectId":117,"rewards":[{"furni":"hween_c20_tentaclethrone","weight":25},{"furni":"hween_c20_tentacletable","weight":25},{"furni":"clothing_tentaclehead","weight":10}]}"""
            ),
            (
                "hween_c20_pandorabox",
                3,
                1,
                false,
                """{"rewardSet":"hween20_1","target":1,"rewards":[{"furni":"hween_r20_evilpandorabox","weight":5},{"furni":"clothing_bloodglasses","weight":7},{"furni":"clothing_bloodjacket","weight":7},{"furni":"clothing_bloodshoes","weight":7},{"furni":"clothing_brain","weight":7},{"furni":"clothing_witchhat2","weight":8},{"furni":"clothing_witchrobes","weight":8},{"furni":"clothing_possessedeyes","weight":8},{"furni":"hween_c18_labglovebox","weight":9},{"furni":"clothing_demonoutfit","weight":10},{"furni":"hween_c16_bed2","weight":10},{"furni":"hween_c15_busstop","weight":10},{"furni":"hween_c19_bewitchedcauldron","weight":13},{"furni":"hween_c17_torturebed","weight":13},{"furni":"hween_c19_fireplace","weight":15}]}"""
            ),
            (
                "hween_r16_crackable2",
                21,
                1,
                false,
                """{"rewardSet":"habboanv_1","target":10,"rewards":[{"furni":"hween_r16_grandpiano"},{"furni":"hween_r16_chandelier"},{"furni":"clothing_r16_catface"},{"furni":"clothing_r16_cyclops"}]}"""
            ),
            (
                "hween_r20_evilpandorabox",
                3,
                1,
                false,
                """{"rewardSet":"hween20_2","target":1,"rewards":[{"furni":"hween_c20_duckgoddess"},{"furni":"hween_c20_evilscarecrow"},{"furni":"hween_c20_eyedemon"},{"furni":"hween_c20_octodemon"}]}"""
            ),
            ("india_c20_blueprint", 3, 1, false, """{"rewardSet":"india20_1","target":1}"""),
            (
                "jungle_c16_flowera1",
                13,
                2,
                true,
                """{"rewardSet":"jung16_1","target":12,"requiredEffectId":192,"finalHitAchievement":"Horticulturist"}"""
            ),
            (
                "jungle_c16_flowera2",
                13,
                2,
                true,
                """{"rewardSet":"jung16_1","target":12,"requiredEffectId":192,"finalHitAchievement":"Horticulturist"}"""
            ),
            (
                "jungle_c16_flowera3",
                13,
                2,
                true,
                """{"rewardSet":"jung16_1","target":12,"requiredEffectId":192,"finalHitAchievement":"Horticulturist"}"""
            ),
            (
                "jungle_c16_flowerb1",
                13,
                2,
                true,
                """{"rewardSet":"jung16_2","target":12,"requiredEffectId":192,"finalHitAchievement":"Horticulturist"}"""
            ),
            (
                "jungle_c16_flowerb2",
                13,
                2,
                true,
                """{"rewardSet":"jung16_2","target":12,"requiredEffectId":192,"finalHitAchievement":"Horticulturist"}"""
            ),
            (
                "jungle_c16_flowerb3",
                13,
                2,
                true,
                """{"rewardSet":"jung16_2","target":12,"requiredEffectId":192,"finalHitAchievement":"Horticulturist"}"""
            ),
            (
                "jungle_c16_flowerc1",
                13,
                2,
                true,
                """{"rewardSet":"jung16_3","target":12,"requiredEffectId":192,"finalHitAchievement":"Horticulturist"}"""
            ),
            (
                "jungle_c16_flowerc2",
                13,
                2,
                true,
                """{"rewardSet":"jung16_3","target":12,"requiredEffectId":192,"finalHitAchievement":"Horticulturist"}"""
            ),
            (
                "jungle_c16_flowerc3",
                13,
                2,
                true,
                """{"rewardSet":"jung16_3","target":12,"requiredEffectId":192,"finalHitAchievement":"Horticulturist"}"""
            ),
            (
                "jungle_c16_flowerd1",
                13,
                2,
                true,
                """{"rewardSet":"jung16_4","target":12,"requiredEffectId":192,"finalHitAchievement":"Horticulturist"}"""
            ),
            (
                "jungle_c16_flowerd2",
                13,
                2,
                true,
                """{"rewardSet":"jung16_4","target":12,"requiredEffectId":192,"finalHitAchievement":"Horticulturist"}"""
            ),
            (
                "jungle_c16_flowerd3",
                13,
                2,
                true,
                """{"rewardSet":"jung16_4","target":12,"requiredEffectId":192,"finalHitAchievement":"Horticulturist"}"""
            ),
            (
                "mystics_crystal_l",
                15,
                2,
                false,
                """{"rewardSet":"crystal_p1","target":1500000,"incrementalHitAchievement":"CrystalCracker","finalHitAchievement":"CrystalLegend"}"""
            ),
            (
                "mystics_crystal_m",
                15,
                2,
                false,
                """{"rewardSet":"crystal_p1","target":1000000,"incrementalHitAchievement":"CrystalCracker","finalHitAchievement":"CrystalLegend"}"""
            ),
            (
                "mystics_crystal_s",
                15,
                2,
                false,
                """{"rewardSet":"crystal_p1","target":500000,"incrementalHitAchievement":"CrystalCracker","finalHitAchievement":"CrystalLegend"}"""
            ),
            (
                "ny16_crackable",
                3,
                1,
                false,
                """{"rewardSet":"ny16_1","target":1,"rewards":[{"furni":"clothing_party3"},{"furni":"clothing_party4"},{"furni":"clothing_party5"},{"furni":"clothing_party6"},{"furni":"clothing_party7"},{"furni":"clothing_party8"}]}"""
            ),
            (
                "ny17_crackable",
                3,
                1,
                false,
                """{"rewardSet":"ny17_1","target":1,"rewards":[{"furni":"clothing_r16_party9"},{"furni":"clothing_r16_party10"},{"furni":"clothing_r16_party11"},{"furni":"clothing_r16_party12"},{"furni":"clothing_r16_party13"},{"furni":"clothing_r16_party14"}]}"""
            ),
            (
                "ny18_crackable",
                3,
                1,
                false,
                """{"rewardSet":"ny18_1","target":1,"rewards":[{"furni":"clothing_mini_bowlerhat_blue"},{"furni":"clothing_mini_bowlerhat_cream"},{"furni":"clothing_mini_bowlerhat_dark"},{"furni":"clothing_mini_bowlerhat_green"},{"furni":"clothing_mini_bowlerhat_gold"},{"furni":"clothing_mini_bowlerhat_purple"},{"furni":"clothing_mini_bowlerhat_red"}]}"""
            ),
            (
                "ny_r18_crackable",
                3,
                1,
                false,
                """{"rewardSet":"ny_r18","target":1,"rewards":[{"furni":"clothing_r18_sparkleparty1"},{"furni":"clothing_r18_sparkleparty2"},{"furni":"clothing_r18_sparkleparty3"},{"furni":"clothing_r18_sparkleparty4"},{"furni":"clothing_r18_sparkleparty5"},{"furni":"clothing_r18_sparkleparty6"},{"furni":"clothing_r18_sparkleparty7"},{"furni":"clothing_r18_sparkleparty8"}]}"""
            ),
            (
                "ny_r19_crackable",
                3,
                1,
                false,
                """{"rewardSet":"ny_r19","target":1,"rewards":[{"furni":"clothing_r19_sparklywaist1"},{"furni":"clothing_r19_sparklywaist2"},{"furni":"clothing_r19_sparklywaist3"},{"furni":"clothing_r19_sparklywaist4"},{"furni":"clothing_r19_sparklywaist5"},{"furni":"clothing_r19_sparklywaist6"},{"furni":"clothing_r19_sparklywaist7"},{"furni":"clothing_r19_sparklywaist8"}]}"""
            ),
            (
                "ny_r20_crackable",
                3,
                1,
                false,
                """{"rewardSet":"ny_r20","target":1,"rewards":[{"furni":"clothing_r20_mask1","weight":16},{"furni":"clothing_r20_mask2","weight":12},{"furni":"clothing_r20_mask3","weight":4},{"furni":"clothing_r20_mask4","weight":16},{"furni":"clothing_r20_mask5","weight":12},{"furni":"clothing_r20_mask6","weight":12},{"furni":"clothing_r20_mask7","weight":12},{"furni":"clothing_r20_mask8","weight":16}]}"""
            ),
            (
                "plushie_c20_crackable",
                3,
                1,
                false,
                """{"rewardSet":"plushie20_1","target":1,"rewardPlacement":"Inventory"}"""
            ),
            (
                "santorini_c17_artefact1",
                13,
                1,
                false,
                """{"rewardSet":"santorini_1","target":12,"requiredEffectId":186,"finalHitAchievement":"Restorer","rewards":[{"furni":"clothing_greektoga"}]}"""
            ),
            (
                "santorini_c17_artefact2",
                13,
                1,
                false,
                """{"rewardSet":"santorini_2","target":12,"requiredEffectId":186,"finalHitAchievement":"Restorer","rewards":[{"furni":"clothing_leafcrown"}]}"""
            ),
            (
                "santorini_c17_artefact3",
                13,
                1,
                false,
                """{"rewardSet":"santorini_3","target":12,"requiredEffectId":186,"finalHitAchievement":"Restorer","rewards":[{"furni":"clothing_hermeshat"}]}"""
            ),
            (
                "santorini_c17_artefact4",
                13,
                1,
                false,
                """{"rewardSet":"santorini_4","target":12,"requiredEffectId":186,"finalHitAchievement":"Restorer","rewards":[{"furni":"clothing_hermesshoes"}]}"""
            ),
            (
                "santorini_c17_artefact5",
                13,
                1,
                false,
                """{"rewardSet":"santorini_5","target":12,"requiredEffectId":186,"finalHitAchievement":"Restorer","rewards":[{"furni":"clothing_hoplitehelm"}]}"""
            ),
            (
                "santorini_r17_chest",
                3,
                1,
                false,
                """{"rewardSet":"santorini_6","target":1,"rewards":[{"furni":"santorini_c17_artefact1"},{"furni":"santorini_c17_artefact2"},{"furni":"santorini_c17_artefact3"},{"furni":"santorini_c17_artefact4"},{"furni":"santorini_c17_artefact5"}]}"""
            ),
            (
                "tokyo_c18_gacha",
                3,
                1,
                false,
                """{"rewardSet":"tokyo_1","target":1,"rewards":[{"furni":"tokyo_c18_toy6"},{"furni":"tokyo_c18_toy4"},{"furni":"tokyo_c18_toy2"},{"furni":"tokyo_c18_toy1"},{"furni":"tokyo_c18_toy9"},{"furni":"tokyo_c18_toy10"},{"furni":"tokyo_c18_toy5"},{"furni":"tokyo_c18_toy3"},{"furni":"tokyo_c18_toy7"},{"furni":"tokyo_c18_toy8"}]}"""
            ),
            (
                "xmas_c16_creature1",
                25,
                1,
                false,
                """{"rewardSet":"xmas16_2","target":12,"requiredEffectId":186,"finalHitAchievement":"CreatureRearer","finalHitAchievementCount":5}"""
            ),
            (
                "xmas_c16_creature4",
                25,
                1,
                false,
                """{"rewardSet":"xmas16_3","target":12,"requiredEffectId":186,"finalHitAchievement":"CreatureRearer","finalHitAchievementCount":10}"""
            ),
            (
                "xmas_c16_creature7",
                25,
                1,
                false,
                """{"rewardSet":"xmas16_4","target":12,"requiredEffectId":186,"finalHitAchievement":"CreatureRearer","finalHitAchievementCount":15}"""
            ),
            (
                "xmas_c16_egg",
                25,
                1,
                false,
                """{"rewardSet":"xmas16_1","target":12,"requiredEffectId":186,"finalHitAchievement":"CreatureRearer","finalHitAchievementCount":5}"""
            ),
            ("xmas_c16_stocking", 3, 1, false, """{"rewardSet":"xmas16_5","target":1}"""),
            ("xmas_c17_book", 3, 1, false, """{"rewardSet":"xmas17_1","target":1}"""),
            ("xmas_c18_doll1", 3, 1, false, """{"rewardSet":"xmas18_1","target":1}"""),
            ("xmas_c18_doll10", 3, 1, false, """{"rewardSet":"xmas18_10","target":1}"""),
            ("xmas_c18_doll2", 3, 1, false, """{"rewardSet":"xmas18_2","target":1}"""),
            ("xmas_c18_doll3", 3, 1, false, """{"rewardSet":"xmas18_3","target":1}"""),
            ("xmas_c18_doll4", 3, 1, false, """{"rewardSet":"xmas18_4","target":1}"""),
            ("xmas_c18_doll5", 3, 1, false, """{"rewardSet":"xmas18_5","target":1}"""),
            ("xmas_c18_doll6", 3, 1, false, """{"rewardSet":"xmas18_6","target":1}"""),
            ("xmas_c18_doll7", 3, 1, false, """{"rewardSet":"xmas18_7","target":1}"""),
            ("xmas_c18_doll8", 3, 1, false, """{"rewardSet":"xmas18_8","target":1}"""),
            ("xmas_c18_doll9", 3, 1, false, """{"rewardSet":"xmas18_9","target":1}"""),
            ("xmas_c19_box1", 3, 1, false, """{"rewardSet":"xmas19_box1","target":1}"""),
            ("xmas_c19_box2", 3, 1, false, """{"rewardSet":"xmas19_box2","target":1}"""),
            ("xmas_c19_box3", 3, 1, false, """{"rewardSet":"xmas19_box3","target":1}"""),
            ("xmas_c19_box4", 3, 1, false, """{"rewardSet":"xmas19_box4","target":1}"""),
            ("xmas_c19_box5", 3, 1, false, """{"rewardSet":"xmas19_box5","target":1}"""),
            ("xmas_c19_box6", 3, 1, false, """{"rewardSet":"xmas19_box6","target":1}"""),
            ("xmas_c20_runerock", 3, 1, false, """{"rewardSet":"xmas20_1","target":1}"""),
            ("xmas_c20_runerockblue", 3, 1, false, """{"rewardSet":"xmas20_2","target":1}"""),
            ("xmas_c20_runerockgreen", 3, 1, false, """{"rewardSet":"xmas20_3","target":1}"""),
            ("xmas_c20_runerockpurple", 3, 1, false, """{"rewardSet":"xmas20_4","target":1}"""),
            ("xmas_c20_runerockred", 3, 1, false, """{"rewardSet":"xmas20_5","target":1}"""),
            ("xmas_c20_runerockyellow", 3, 1, false, """{"rewardSet":"xmas20_6","target":1}"""),
        ];

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            foreach (var (name, states, usage, walkable, crackable) in CRACKABLES)
                migrationBuilder.Sql(
                    $"UPDATE `furniture_definitions` SET `logic` = '{LOGIC}', `total_states` = {states}, `usage_policy` = {usage}, "
                        + (walkable ? "`can_walk` = 1, " : "")
                        + $"`extra_data` = IF(JSON_VALID(`extra_data`), JSON_SET(`extra_data`, '$.crackable', JSON_EXTRACT('{crackable}', '$')), "
                        + $"JSON_OBJECT('crackable', JSON_EXTRACT('{crackable}', '$'))) WHERE `name` = '{name}';"
                );
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // What MapCrackableFurni wrote before is not kept anywhere; its own Down takes the
            // logic away again.
        }
    }
}
