using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Turbo.Database.Context;

#nullable disable

namespace Turbo.Database.Migrations
{
    /// <summary>
    /// Points every furni that hands out hand items in Sulake's furni data at the vending logic:
    /// the fridges, drinks and snack machines (<c>VendingMachineFurni</c>), ice cream machines
    /// (<c>IceCreamMachineFurni</c>) and the static providers (<c>HandItemProviderFurni</c>), with
    /// the hand items its <c>&lt;drinks&gt;</c> lists, whether it shows a dispensing state (the
    /// static providers do not) and its usage (<c>&lt;everyone-can-use/&gt;</c>, which all but
    /// three carry; room rights otherwise). Only a definition still on the plain default logic is
    /// taken over, so a furni the hotel gave other behaviour keeps it, and one this hotel does not
    /// have is left alone. Data only: the model is unchanged, so there is no designer snapshot.
    /// </summary>
    [DbContext(typeof(TurboDbContext))]
    [Migration("20261008200000_MapVendingFurni")]
    public partial class MapVendingFurni : Migration
    {
        private const string LOGIC = "vending_machine";

        /// <summary>Name, the usage policy (2 everyone, 1 room rights), the <c>vending</c> section.</summary>
        private static readonly (string Name, int Usage, string Vending)[] VENDING =
        [
            ("ads_711", 2, """{"handItems":[33]}"""),
            ("ads_calip_cola", 2, """{"handItems":[26]}"""),
            ("ads_cheetos", 2, """{"handItems":[52]}"""),
            ("ads_cheetos_hotdog", 2, """{"handItems":[56]}"""),
            ("ads_chocapic", 2, """{"handItems":[54]}"""),
            ("ads_chups", 2, """{"handItems":[48]}"""),
            ("ads_cl_moodi", 2, """{"handItems":[45,46,47]}"""),
            ("ads_clearasil_vend", 2, """{"handItems":[1046],"animates":false}"""),
            ("ads_clearasil_vend2", 2, """{"handItems":[1046],"animates":false}"""),
            ("ads_dfrisss", 2, """{"handItems":[72]}"""),
            ("ads_droetker_paula", 2, """{"handItems":[49]}"""),
            ("ads_dtlrare", 2, """{"handItems":[1048],"animates":false}"""),
            ("ads_dtlrare_2", 2, """{"handItems":[1052],"animates":false}"""),
            ("ads_dtlrare_rc", 2, """{"handItems":[1052],"animates":false}"""),
            ("ads_grefusa_yum", 2, """{"handItems":[51]}"""),
            ("ads_hh_safe", 2, """{"handItems":[59]}"""),
            ("ads_honeymonster", 2, """{"handItems":[1028],"animates":false}"""),
            ("ads_liisu", 2, """{"handItems":[1]}"""),
            ("ads_mall_coffeem", 2, """{"handItems":[41]}"""),
            ("ads_oc_soda", 2, """{"handItems":[42]}"""),
            ("ads_oc_soda_cherry", 2, """{"handItems":[57]}"""),
            ("ads_pepsi0", 2, """{"handItems":[55]}"""),
            ("ads_sunnyvend", 2, """{"handItems":[61]}"""),
            ("ads_suun", 2, """{"handItems":[1]}"""),
            ("antibully_machine", 2, """{"handItems":[1095],"animates":false}"""),
            ("arabian_teamk", 2, """{"handItems":[27]}"""),
            ("army_c15_compass", 2, """{"handItems":[1072],"animates":false}"""),
            ("attic15_chest", 2, """{"handItems":[1065,1066,1067],"animates":false}"""),
            ("bar_armas", 2, """{"handItems":[1,2]}"""),
            ("bar_basic", 2, """{"handItems":[1,2]}"""),
            ("bar_polyfon", 2, """{"handItems":[1,2]}"""),
            ("bathroom_sinkmodule1", 2, """{"handItems":[18]}"""),
            ("bathroom_sinkmodule2", 2, """{"handItems":[18]}"""),
            ("bathroom_sinkmodule3", 2, """{"handItems":[18]}"""),
            ("bathroom_sinkmodule4", 2, """{"handItems":[18]}"""),
            ("bathroom_toiletroll", 2, """{"handItems":[1059],"animates":false}"""),
            ("bazaar_c17_bubblejuiceblower", 2, """{"handItems":[19],"animates":false}"""),
            ("bazaar_c17_chillies", 2, """{"handItems":[112],"animates":false}"""),
            ("bazaar_c17_sticklizard", 2, """{"handItems":[1078],"animates":false}"""),
            ("bazaar_r17_fountain", 2, """{"handItems":[18]}"""),
            ("bling11_slot", 2, """{"handItems":[32,35,40],"animates":false}"""),
            ("bling_fridge", 2, """{"handItems":[35]}"""),
            ("bling_fridge_restricted", 2, """{"handItems":[50]}"""),
            ("bolly_phant", 2, """{"handItems":[35]}"""),
            ("bolly_vase", 2, """{"handItems":[1019],"animates":false}"""),
            ("bonusrare18_1", 2, """{"handItems":[113,114,115],"animates":false}"""),
            ("bonusrare20_3", 2, """{"handItems":[53],"animates":false}"""),
            ("calippo", 2, """{"handItems":[26]}"""),
            ("china_c21_orangebasket", 2, """{"handItems":[38],"animates":false}"""),
            ("cine_popcorn", 2, """{"handItems":[63]}"""),
            ("cland15_flosstree", 2, """{"handItems":[92,93,94,95,79],"animates":false}"""),
            ("cland15_unipoo", 2, """{"handItems":[4,75,76,77],"animates":false}"""),
            ("cland_c15_swirltree", 2, """{"handItems":[92,93,94,95],"animates":false}"""),
            ("classic2_burger", 2, """{"handItems":[109],"animates":false}"""),
            ("classic2_drinkmach", 2, """{"handItems":[18,1,29,30,42,66],"animates":false}"""),
            ("classic2_drinkmach2", 2, """{"handItems":[18,1,29,30,42,66],"animates":false}"""),
            ("classic2_grill", 2, """{"handItems":[109],"animates":false}"""),
            ("classic3_ticket", 2, """{"handItems":[1070],"animates":false}"""),
            ("classic7_drinkcabinet", 2, """{"handItems":[42,43,66],"animates":false}"""),
            ("classic7_drinkdispenser", 1, """{"handItems":[29,30],"animates":false}"""),
            ("classic7_fridge", 2, """{"handItems":[42,43,66],"animates":false}"""),
            ("country_well", 2, """{"handItems":[7]}"""),
            (
                "cpunk_c15_bar",
                2,
                """{"handItems":[35,53,62,1041,87,90,24,29,30],"animates":false}"""
            ),
            ("diner_gumvendor", 2, """{"handItems":[67,67,67,69,69,69,68],"animates":false}"""),
            ("dino_c15_nest", 2, """{"handItems":[1073,1074,1075,1076],"animates":false}"""),
            ("dtl_r20_gold", 2, """{"handItems":[1093],"animates":false}"""),
            ("easel_5", 2, """{"handItems":[1051],"animates":false}"""),
            ("easter14_palmtree", 2, """{"handItems":[1050],"animates":false}"""),
            ("easter_c17_appletree", 2, """{"handItems":[83],"animates":false}"""),
            ("easter_c17_peachtree", 2, """{"handItems":[37],"animates":false}"""),
            ("easter_c17_peartree", 2, """{"handItems":[36],"animates":false}"""),
            ("easter_c18_lemontree", 2, """{"handItems":[116],"animates":false}"""),
            ("easter_c18_veg", 2, """{"handItems":[98],"animates":false}"""),
            ("easter_c20_fishingpole", 2, """{"handItems":[1090,1091,1092],"animates":false}"""),
            ("eco_fruits1", 2, """{"handItems":[36,37,38,39]}"""),
            ("eco_fruits2", 2, """{"handItems":[36,37,38,39]}"""),
            ("eco_fruits3", 2, """{"handItems":[36,37,38,39]}"""),
            ("eco_tree1", 2, """{"handItems":[38]}"""),
            ("eco_tree2", 2, """{"handItems":[36]}"""),
            ("es_roaster", 2, """{"handItems":[60]}"""),
            ("exe_drinks_cabinet", 2, """{"handItems":[40]}"""),
            ("exe_icecream", 2, """{"handItems":[4]}"""),
            ("fest_c19_bobbatea", 2, """{"handItems":[124,125,126],"animates":false}"""),
            ("fest_c19_coalicecream", 2, """{"handItems":[127,128],"animates":false}"""),
            ("fridge", 2, """{"handItems":[3,4,5,6]}"""),
            ("garden_flo1", 2, """{"handItems":[1007]}"""),
            ("garden_flo2", 2, """{"handItems":[1008]}"""),
            ("garden_flo3", 2, """{"handItems":[1009]}"""),
            ("gift_c18_cookiejar", 2, """{"handItems":[117],"animates":false}"""),
            ("giftflowers", 2, """{"handItems":[1006],"animates":false}"""),
            ("gold_c15_arc_hole", 2, """{"handItems":[34],"animates":false}"""),
            ("gothic_bowl", 2, """{"handItems":[62]}"""),
            ("hal_cauldron", 2, """{"handItems":[3]}"""),
            ("hblooza14_cafe_b", 2, """{"handItems":[85,86],"animates":false}"""),
            ("hblooza14_cafe_p", 2, """{"handItems":[85,86],"animates":false}"""),
            ("hblooza14_cafe_y", 2, """{"handItems":[85,86],"animates":false}"""),
            ("hblooza14_candystall", 2, """{"handItems":[84,63,79,80,48],"animates":false}"""),
            (
                "hblooza14_drinkstall",
                2,
                """{"handItems":[6,24,30,32,57,66,67,72],"animates":false}"""
            ),
            ("hblooza14_duckhook", 2, """{"handItems":[1053],"animates":false}"""),
            ("hblooza14_duckhookhc", 2, """{"handItems":[1036],"animates":false}"""),
            ("hblooza_bubblejuice", 2, """{"handItems":[19],"animates":false}"""),
            ("hblooza_candyfloss", 2, """{"handItems":[79,80],"animates":false}"""),
            ("hblooza_chicken", 2, """{"handItems":[70],"animates":false}"""),
            ("hblooza_hotdog", 2, """{"handItems":[81],"animates":false}"""),
            ("hblooza_icecream", 2, """{"handItems":[4,75,76,77],"animates":false}"""),
            ("hblooza_kiosk", 2, """{"handItems":[1,3,19,31,36,38,63,81,1036],"animates":false}"""),
            ("hblooza_popcorn", 2, """{"handItems":[63],"animates":false}"""),
            ("hc16_3", 2, """{"handItems":[50],"animates":false}"""),
            ("hc17_11", 2, """{"handItems":[35]}"""),
            ("hc21_1", 2, """{"handItems":[1096],"animates":false}"""),
            ("hc21_11", 2, """{"handItems":[3,36,83,100,103,107],"animates":false}"""),
            ("hc2_coffee", 2, """{"handItems":[53]}"""),
            ("hc_arab_teamk", 2, """{"handItems":[27]}"""),
            ("hc_btlr", 2, """{"handItems":[24]}"""),
            ("hcc_minibar", 2, """{"handItems":[3]}"""),
            ("hosp_c19_drinksvend", 2, """{"handItems":[29,30,42,43],"animates":false}"""),
            ("hosptl_bed", 2, """{"handItems":[1011],"animates":false}"""),
            ("hosptl_cab1", 2, """{"handItems":[1011,1013,1014,1015],"animates":false}"""),
            ("hosptl_cab2", 2, """{"handItems":[1011,1013,1014,1015],"animates":false}"""),
            ("hween08_sink", 2, """{"handItems":[29]}"""),
            ("hween08_sink2", 2, """{"handItems":[30]}"""),
            ("hween10_zombie", 2, """{"handItems":[58],"animates":false}"""),
            ("hween11_punch", 2, """{"handItems":[34,58,29]}"""),
            (
                "hween12_grabby",
                2,
                """{"handItems":[1035,1037,1038,1039,1040,1041,1042,1044,1045],"animates":false}"""
            ),
            ("hween13_tree", 2, """{"handItems":[83],"animates":false}"""),
            ("hween14_altarpieces3", 2, """{"handItems":[1061],"animates":false}"""),
            ("hween_c18_labshelf", 2, """{"handItems":[1043,1044],"animates":false}"""),
            ("hween_c18_medicineshelf", 2, """{"handItems":[44,19,1014],"animates":false}"""),
            (
                "hween_c18_spareparts",
                2,
                """{"handItems":[58,1015,1035,1039,1040,1045],"animates":false}"""
            ),
            ("hween_c19_pumpkinpatch", 2, """{"handItems":[1083],"animates":false}"""),
            ("hween_r18_antiquechemset", 2, """{"handItems":[44]}"""),
            ("hyacinth1", 2, """{"handItems":[1021],"animates":false}"""),
            ("hyacinth2", 2, """{"handItems":[1022],"animates":false}"""),
            ("joulutahti", 2, """{"handItems":[1023],"animates":false}"""),
            ("joulutahti_notrd", 2, """{"handItems":[1023],"animates":false}"""),
            ("jp_teamaker", 2, """{"handItems":[28]}"""),
            ("js_bling_fridge", 2, """{"handItems":[35]}"""),
            ("js_c16_drkcab", 2, """{"handItems":[43],"animates":false}"""),
            ("jungle_c16_bush", 2, """{"handItems":[1006,1037,1038],"animates":false}"""),
            ("ktchn15_bubblejuicerack", 2, """{"handItems":[24,29,50,74,101],"animates":false}"""),
            ("ktchn15_coffeemaker", 2, """{"handItems":[41,53],"animates":false}"""),
            ("ktchn15_fridge", 2, """{"handItems":[3,36,37,38,39]}"""),
            ("ktchn_fridge", 2, """{"handItems":[3,36,37,38,39]}"""),
            ("ktchn_inspctr", 2, """{"handItems":[34]}"""),
            ("limo_b_mid3", 2, """{"handItems":[40]}"""),
            ("lm_bananadrink", 2, """{"handItems":[66]}"""),
            ("mall_c17_kiosk", 2, """{"handItems":[37,36,83,29,30,34,42,38],"animates":false}"""),
            ("mall_r17_coffeem", 2, """{"handItems":[41],"animates":false}"""),
            (
                "market_c19_dairyfridge",
                2,
                """{"handItems":[107,129,130,42,43,66,113,114,115],"animates":false}"""
            ),
            ("market_c19_deli1", 2, """{"handItems":[34,81,111,132,136],"animates":false}"""),
            ("market_c19_deli2", 2, """{"handItems":[39,71,84,89,130,131,135],"animates":false}"""),
            ("market_c19_drygoods", 2, """{"handItems":[63,1028,117,138,1089],"animates":false}"""),
            ("market_c19_dvds", 2, """{"handItems":[1085,1086],"animates":false}"""),
            (
                "market_c19_icecreamfreezer",
                2,
                """{"handItems":[137,4,75,76,77,127,128],"animates":false}"""
            ),
            (
                "market_c19_icecreamtubs",
                2,
                """{"handItems":[4,75,76,77,127,128,137],"animates":false}"""
            ),
            ("market_c19_meat", 2, """{"handItems":[136,70,81,109,122],"animates":false}"""),
            (
                "market_c19_stationary",
                2,
                """{"handItems":[1087,1088,1003,1068,1069,1070,1004,1005],"animates":false}"""
            ),
            (
                "market_c19_vegfruit",
                2,
                """{"handItems":[3,36,37,38,83,98,99,100,112,116,133,134,1084],"animates":false}"""
            ),
            (
                "matic_dispenser",
                2,
                """{"handItems":[1032,1033,1034,1035,1036,1037,1038,1032,1033,1034,1035,1036,1037,1038,1,3,28,29,34,36,37,38,39,58,70,71,1013,1014,1015,1019,1029,1051,1031],"animates":false}"""
            ),
            ("matic_slime_duck", 2, """{"handItems":[1036],"animates":false}"""),
            ("matic_water_dispenser", 2, """{"handItems":[18],"animates":false}"""),
            ("md_limukaappi", 2, """{"handItems":[19]}"""),
            ("mm_lemon_drink", 2, """{"handItems":[64]}"""),
            ("mocchamaster", 2, """{"handItems":[8,9,10,11,12,13,14,15,16,17]}"""),
            ("ny2015_bar", 2, """{"handItems":[35],"animates":false}"""),
            ("ny2015_cctray", 2, """{"handItems":[89],"animates":false}"""),
            ("ny2015_drktray", 2, """{"handItems":[90],"animates":false}"""),
            ("olympics_c16_cadorack", 2, """{"handItems":[104],"animates":false}"""),
            ("olympics_c16_graperack", 2, """{"handItems":[105],"animates":false}"""),
            ("olympics_c16_merch", 2, """{"handItems":[102],"animates":false}"""),
            ("olympics_c16_nanarack", 1, """{"handItems":[103],"animates":false}"""),
            ("olympics_c16_weightrack", 2, """{"handItems":[108],"animates":false}"""),
            ("olympics_r16_smoothie", 2, """{"handItems":[106],"animates":false}"""),
            ("olympics_r16_vendingmchn", 2, """{"handItems":[107],"animates":false}"""),
            ("paris15_cake", 2, """{"handItems":[96],"animates":false}"""),
            ("paris_c15_breadstall", 2, """{"handItems":[97],"animates":false}"""),
            (
                "paris_c15_flowerstl",
                2,
                """{"handItems":[1000,1001,1002,1006,1007,1008,1009,1019,1021,1022],"animates":false}"""
            ),
            ("paris_c15_vegstall1", 2, """{"handItems":[100],"animates":false}"""),
            ("paris_c15_vegstall2", 2, """{"handItems":[99],"animates":false}"""),
            ("paris_c15_vegstall3", 2, """{"handItems":[98],"animates":false}"""),
            ("party_tray", 2, """{"handItems":[31]}"""),
            ("pcnc_carrot", 2, """{"handItems":[3]}"""),
            ("pirate_barrel2", 2, """{"handItems":[38],"animates":false}"""),
            ("pirate_barrel3", 2, """{"handItems":[34],"animates":false}"""),
            ("pirate_cannonballs", 2, """{"handItems":[1047],"animates":false}"""),
            ("pirate_navdesk", 2, """{"handItems":[82],"animates":false}"""),
            ("plant_rose", 2, """{"handItems":[1000],"animates":false}"""),
            ("plant_rose_black", 2, """{"handItems":[1001],"animates":false}"""),
            ("plant_sunflower", 2, """{"handItems":[1002],"animates":false}"""),
            ("pudding", 2, """{"handItems":[1024],"animates":false}"""),
            ("purablk_c16_bar", 2, """{"handItems":[1,2],"animates":false}"""),
            ("purablk_c16_fridge", 2, """{"handItems":[3,4,5,6],"animates":false}"""),
            ("qt_sum11_ictrolley", 2, """{"handItems":[4]}"""),
            ("qt_xm10_elephant", 2, """{"handItems":[35]}"""),
            ("rainbow_c19_flags", 2, """{"handItems":[1082],"animates":false}"""),
            ("rare_blackrosegold_icecream", 2, """{"handItems":[4],"animates":false}"""),
            ("rare_colourable_icecream", 2, """{"handItems":[4]}"""),
            ("rare_icecream", 2, """{"handItems":[4]}"""),
            ("rare_icecream_campaign", 2, """{"handItems":[4]}"""),
            ("rare_r21_coffeesiphon", 2, """{"handItems":[146],"animates":false}"""),
            ("room_cof15_counter1", 2, """{"handItems":[89,1024,1053],"animates":false}"""),
            (
                "room_cof15_cup",
                2,
                """{"handItems":[8,9,10,11,12,13,14,15,16,17,53,54],"animates":false}"""
            ),
            ("room_cof15_cup2", 2, """{"handItems":[85,86],"animates":false}"""),
            ("room_cof15_shelf", 2, """{"handItems":[1003,1004,1005],"animates":false}"""),
            ("room_info15_fridge", 2, """{"handItems":[42],"animates":false}"""),
            ("room_pcnc15_carrot", 2, """{"handItems":[3],"animates":false}"""),
            ("room_pcnc15_hotdog", 2, """{"handItems":[81],"animates":false}"""),
            ("room_pcnc15_soda", 2, """{"handItems":[42,43],"animates":false}"""),
            ("room_thr15_bubjuice", 2, """{"handItems":[19],"animates":false}"""),
            ("room_thr15_candy", 2, """{"handItems":[79,80,84,48,67,68,69],"animates":false}"""),
            ("room_thr15_hotdog", 2, """{"handItems":[81],"animates":false}"""),
            ("room_thr15_icecream", 2, """{"handItems":[4,75,76,77],"animates":false}"""),
            ("room_thr15_popcorn", 2, """{"handItems":[63],"animates":false}"""),
            ("room_wl15_mag1", 2, """{"handItems":[1068,1069,1070],"animates":false}"""),
            ("room_wlof15_bookcase", 2, """{"handItems":[1003,1004,1005],"animates":false}"""),
            ("safe_silo", 2, """{"handItems":[17]}"""),
            ("safe_silo_pb", 2, """{"handItems":[3]}"""),
            ("samovar", 2, """{"handItems":[1]}"""),
            ("santorini_c17_rockpool", 2, """{"handItems":[111],"animates":false}"""),
            ("sb_cans", 1, """{"handItems":[1060],"animates":false}"""),
            ("school_cafe", 2, """{"handItems":[71,36,37,3],"animates":false}"""),
            ("sf_mbar", 2, """{"handItems":[44]}"""),
            ("shelves_silo", 2, """{"handItems":[1003,1004,1005]}"""),
            ("sink", 2, """{"handItems":[18]}"""),
            ("st_hween14_skulls", 2, """{"handItems":[1062,1063,1064],"animates":false}"""),
            ("st_palooza_balloons", 2, """{"handItems":[1054,1055,1056,1057],"animates":false}"""),
            ("summer_c17_burgertruck", 2, """{"handItems":[109],"animates":false}"""),
            ("summer_icebox", 2, """{"handItems":[43]}"""),
            ("suncity_c19_wateroutlet", 2, """{"handItems":[1081],"animates":false}"""),
            ("sunsetcafe_c20_coffeemachine", 2, """{"handItems":[53],"animates":false}"""),
            ("tablet_vendor", 2, """{"handItems":[1030],"animates":false}"""),
            ("tablet_vendorg", 2, """{"handItems":[1071],"animates":false}"""),
            ("toaster", 2, """{"handItems":[71],"animates":false}"""),
            ("tokyo_c18_bugsmachine", 2, """{"handItems":[1079,1080,1043],"animates":false}"""),
            ("tokyo_c18_drinksmachine", 2, """{"handItems":[118,119,42,43,66],"animates":false}"""),
            ("tokyo_c18_snackdisplay", 2, """{"handItems":[122],"animates":false}"""),
            ("tokyo_c18_snackdisplay2", 2, """{"handItems":[120,121],"animates":false}"""),
            ("track12_mini_torch", 2, """{"handItems":[1031],"animates":false}"""),
            ("track12_tea_mother", 2, """{"handItems":[10]}"""),
            ("tray_glasstower", 2, """{"handItems":[40]}"""),
            ("turkey", 2, """{"handItems":[70],"animates":false}"""),
            ("uni_fridge", 2, """{"handItems":[18,3,29,30,34,36,37],"animates":false}"""),
            ("val13_easel_1", 2, """{"handItems":[1051],"animates":false}"""),
            ("val13_easel_2", 2, """{"handItems":[1051],"animates":false}"""),
            ("val13_easel_3", 2, """{"handItems":[1051],"animates":false}"""),
            ("val13_easel_4", 2, """{"handItems":[1051],"animates":false}"""),
            ("val13_easel_5", 2, """{"handItems":[1051],"animates":false}"""),
            ("val15_tea", 2, """{"handItems":[91],"animates":false}"""),
            ("val_c20_chocfountain", 2, """{"handItems":[143,144],"animates":false}"""),
            ("val_cauldron", 2, """{"handItems":[25]}"""),
            ("vikings_basket1", 2, """{"handItems":[3,36,37],"animates":false}"""),
            ("vikings_basket2", 2, """{"handItems":[34,70,1035,1040],"animates":false}"""),
            ("wildwest_cabinet", 2, """{"handItems":[88],"animates":false}"""),
            ("wildwest_light", 2, """{"handItems":[1058],"animates":false}"""),
            ("wildwest_pump", 2, """{"handItems":[87],"animates":false}"""),
            ("xm09_cocoa", 2, """{"handItems":[15]}"""),
            ("xmas08_hole", 2, """{"handItems":[34]}"""),
            ("xmas11_balloon", 2, """{"handItems":[1029],"animates":false}"""),
            ("xmas11_btlr", 2, """{"handItems":[15]}"""),
            ("xmas12_barrel", 2, """{"handItems":[73],"animates":false}"""),
            ("xmas12_nutcracker", 2, """{"handItems":[60],"animates":false}"""),
            ("xmas13_candycane1", 2, """{"handItems":[48,1025,84],"animates":false}"""),
            ("xmas13_eggnogbowl", 2, """{"handItems":[73],"animates":false}"""),
            ("xmas13_gingerbread", 2, """{"handItems":[84],"animates":false}"""),
            ("xmas13_icecream", 2, """{"handItems":[4]}"""),
            ("xmas13_snowflake7", 2, """{"handItems":[18]}"""),
            ("xmas13_toolbox", 2, """{"handItems":[1049],"animates":false}"""),
            ("xmas14_tikibar", 2, """{"handItems":[31],"animates":false}"""),
            ("xmas14_tikibar2", 2, """{"handItems":[31],"animates":false}"""),
            ("xmas15_nutcrackerltd", 2, """{"handItems":[60],"animates":false}"""),
            ("xmas_c15_store1", 2, """{"handItems":[1065,1066,1067,1026,1053],"animates":false}"""),
            ("xmas_c15_store2", 2, """{"handItems":[95,94,93,92,67,68,69,48],"animates":false}"""),
            ("xmas_c15_store3", 2, """{"handItems":[81],"animates":false}"""),
            ("xmas_c15_store4", 2, """{"handItems":[84],"animates":false}"""),
            ("xmas_c16_mailshelf", 2, """{"handItems":[110],"animates":false}"""),
            ("xmas_c17_chestnutstall", 2, """{"handItems":[60],"animates":false}"""),
            ("xmas_c18_borscht", 2, """{"handItems":[123],"animates":false}"""),
            ("xmas_c19_stackedicedrinks", 2, """{"handItems":[142],"animates":false}"""),
            ("xmas_giftbag", 2, """{"handItems":[1025,1026,1027],"animates":false}"""),
            ("xmas_r20_magicsword", 2, """{"handItems":[1094],"animates":false}"""),
        ];

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            foreach (var (name, usage, vending) in VENDING)
                migrationBuilder.Sql(
                    $"UPDATE `furniture_definitions` SET `logic` = '{LOGIC}', `usage_policy` = {usage}, "
                        + $"`extra_data` = IF(JSON_VALID(`extra_data`), JSON_SET(`extra_data`, '$.vending', JSON_EXTRACT('{vending}', '$')), "
                        + $"JSON_OBJECT('vending', JSON_EXTRACT('{vending}', '$'))) "
                        + $"WHERE `name` = '{name}' AND `logic` IN ('default_floor', 'none', '', '{LOGIC}');"
                );
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder) =>
            migrationBuilder.Sql(
                $"UPDATE `furniture_definitions` SET `logic` = 'default_floor', `extra_data` = "
                    + "IF(JSON_VALID(`extra_data`) AND JSON_LENGTH(JSON_REMOVE(`extra_data`, '$.vending')) > 0, JSON_REMOVE(`extra_data`, '$.vending'), "
                    + $"IF(JSON_VALID(`extra_data`), NULL, `extra_data`)) WHERE `logic` = '{LOGIC}';"
            );
    }
}
