using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Turbo.Database.Context;

#nullable disable

namespace Turbo.Database.Migrations
{
    /// <summary>
    /// Maps the 136 crackables Habbo released after Sulake's XML furni data stops (2021 to 2026),
    /// from its Unity furni data (server class and state count) and the Habbox Wiki campaign pages
    /// (contents, odds, and the effect a hit needs). As in <c>RefineCrackableFurni</c>:
    /// <list type="bullet">
    /// <item>the target is the hits the wiki gives, else the asset's last state for one with more
    /// than three states (a hit a state), else one;</item>
    /// <item><c>EffectDependentCrackableRuntime</c> is only hit wearing its effect (the Golden
    /// Spotlight, a torch, a watering can...; the Fossil Rock takes either pickaxe);</item>
    /// <item><c>PublicCrackableProductRewardFurniture</c> is everyone's and rewards whoever cracks
    /// it, the rest are hit with room rights and reward the owner;</item>
    /// <item><c>CrackableInventoryProductRewardFurniture</c> puts its reward in the inventory, the
    /// others on the crackable's tile.</item>
    /// </list>
    /// An outcome of several furni (three Fallen Angel decorations at once) is one reward with
    /// <c>also</c>; a bonus bag holds its six rares, 5 credits or 3 days of Habbo Club. 128 hold
    /// what a source lists; the rest take hits but are not cracked until a hotel lists their
    /// <c>rewards</c>. Only a definition still on a default logic (or already crackable) is
    /// changed. Data only: the model is unchanged, so there is no designer snapshot.
    /// </summary>
    [DbContext(typeof(TurboDbContext))]
    [Migration("20261008210000_MapNewerCrackableFurni")]
    public partial class MapNewerCrackableFurni : Migration
    {
        private const string LOGIC = "crackable";

        /// <summary>Name, the asset's state count, the usage policy (2 everyone, 1 room rights), the <c>crackable</c> section.</summary>
        private static readonly (
            string Name,
            int States,
            int Usage,
            string Crackable
        )[] CRACKABLES =
        [
            (
                "bonusbag22_1",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"bonusrare22_1*0"},{"furni":"bonusrare22_1*1"},{"furni":"bonusrare22_1*2"},{"furni":"bonusrare22_1*3"},{"furni":"bonusrare22_1*4"},{"furni":"bonusrare22_1*5"},{"credits":5,"weight":1},{"subscription":"HabboClub","subscriptionDays":3,"weight":1}]}"""
            ),
            (
                "bonusbag22_2",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"bonusrare22_2*0"},{"furni":"bonusrare22_2*1"},{"furni":"bonusrare22_2*2"},{"furni":"bonusrare22_2*3"},{"furni":"bonusrare22_2*4"},{"furni":"bonusrare22_2*5"},{"credits":5,"weight":1},{"subscription":"HabboClub","subscriptionDays":3,"weight":1}]}"""
            ),
            (
                "bonusbag22_3",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"bonusrare22_3*0"},{"furni":"bonusrare22_3*1"},{"furni":"bonusrare22_3*2"},{"furni":"bonusrare22_3*3"},{"furni":"bonusrare22_3*4"},{"furni":"bonusrare22_3*5"},{"credits":5,"weight":1},{"subscription":"HabboClub","subscriptionDays":3,"weight":1}]}"""
            ),
            (
                "bonusbag22_4",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"bonusrare22_4*0"},{"furni":"bonusrare22_4*1"},{"furni":"bonusrare22_4*2"},{"furni":"bonusrare22_4*3"},{"furni":"bonusrare22_4*4"},{"furni":"bonusrare22_4*5"},{"credits":5,"weight":1},{"subscription":"HabboClub","subscriptionDays":3,"weight":1}]}"""
            ),
            (
                "bonusbag23_1",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"bonusrare23_1*0"},{"furni":"bonusrare23_1*1"},{"furni":"bonusrare23_1*2"},{"furni":"bonusrare23_1*3"},{"furni":"bonusrare23_1*4"},{"furni":"bonusrare23_1*5"},{"credits":5,"weight":1},{"subscription":"HabboClub","subscriptionDays":3,"weight":1}]}"""
            ),
            (
                "bonusbag23_2",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"bonusrare23_2*0"},{"furni":"bonusrare23_2*1"},{"furni":"bonusrare23_2*2"},{"furni":"bonusrare23_2*3"},{"furni":"bonusrare23_2*4"},{"furni":"bonusrare23_2*5"},{"credits":5,"weight":1},{"subscription":"HabboClub","subscriptionDays":3,"weight":1}]}"""
            ),
            (
                "bonusbag23_3",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"bonusrare23_3*0"},{"furni":"bonusrare23_3*1"},{"furni":"bonusrare23_3*2"},{"furni":"bonusrare23_3*3"},{"furni":"bonusrare23_3*4"},{"furni":"bonusrare23_3*5"},{"credits":5,"weight":1},{"subscription":"HabboClub","subscriptionDays":3,"weight":1}]}"""
            ),
            (
                "bonusbag23_4",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"bonusrare23_4*0"},{"furni":"bonusrare23_4*1"},{"furni":"bonusrare23_4*2"},{"furni":"bonusrare23_4*3"},{"furni":"bonusrare23_4*4"},{"furni":"bonusrare23_4*5"},{"credits":5,"weight":1},{"subscription":"HabboClub","subscriptionDays":3,"weight":1}]}"""
            ),
            (
                "bonusbag24_1",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"bonusrare24_1_a*1"},{"furni":"bonusrare24_1_a*2"},{"furni":"bonusrare24_1_a*3"},{"furni":"bonusrare24_1_a*4"},{"furni":"bonusrare24_1_a*5"},{"furni":"bonusrare24_1_a*6"},{"credits":5,"weight":1},{"subscription":"HabboClub","subscriptionDays":3,"weight":1}]}"""
            ),
            (
                "bonusbag24_2",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"bonusrare24_2*0"},{"furni":"bonusrare24_2*1"},{"furni":"bonusrare24_2*2"},{"furni":"bonusrare24_2*3"},{"furni":"bonusrare24_2*4"},{"furni":"bonusrare24_2*5"},{"credits":5,"weight":1},{"subscription":"HabboClub","subscriptionDays":3,"weight":1}]}"""
            ),
            (
                "bonusbag24_3",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"bonusrare24_3_a*1"},{"furni":"bonusrare24_3_a*2"},{"furni":"bonusrare24_3_a*3"},{"furni":"bonusrare24_3_a*4"},{"furni":"bonusrare24_3_a*5"},{"furni":"bonusrare24_3_a*6"},{"credits":5,"weight":1},{"subscription":"HabboClub","subscriptionDays":3,"weight":1}]}"""
            ),
            (
                "bonusbag24_4",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"bonusrare24_4*0"},{"furni":"bonusrare24_4*1"},{"furni":"bonusrare24_4*2"},{"furni":"bonusrare24_4*3"},{"furni":"bonusrare24_4*4"},{"furni":"bonusrare24_4*5"},{"credits":5,"weight":1},{"subscription":"HabboClub","subscriptionDays":3,"weight":1}]}"""
            ),
            (
                "bonusbag25_1",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"bonusrare25_1*0"},{"furni":"bonusrare25_1*1"},{"furni":"bonusrare25_1*2"},{"furni":"bonusrare25_1*3"},{"furni":"bonusrare25_1*4"},{"furni":"bonusrare25_1*5"},{"credits":5,"weight":1},{"subscription":"HabboClub","subscriptionDays":3,"weight":1}]}"""
            ),
            (
                "bonusbag25_2",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"bonusrare25_2*0"},{"furni":"bonusrare25_2*1"},{"furni":"bonusrare25_2*2"},{"furni":"bonusrare25_2*3"},{"furni":"bonusrare25_2*4"},{"furni":"bonusrare25_2*5"},{"credits":5,"weight":1},{"subscription":"HabboClub","subscriptionDays":3,"weight":1}]}"""
            ),
            (
                "bonusbag25_3",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"bonusrare25_3*0"},{"furni":"bonusrare25_3*1"},{"furni":"bonusrare25_3*2"},{"furni":"bonusrare25_3*3"},{"furni":"bonusrare25_3*4"},{"furni":"bonusrare25_3*5"},{"credits":5,"weight":1},{"subscription":"HabboClub","subscriptionDays":3,"weight":1}]}"""
            ),
            (
                "bonusbag25_4",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"bonusrare25_4*0"},{"furni":"bonusrare25_4*1"},{"furni":"bonusrare25_4*2"},{"furni":"bonusrare25_4*3"},{"furni":"bonusrare25_4*4"},{"furni":"bonusrare25_4*5"},{"credits":5,"weight":1},{"subscription":"HabboClub","subscriptionDays":3,"weight":1}]}"""
            ),
            (
                "bonusbag26_1",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"bonusrare26_1*0"},{"furni":"bonusrare26_1*1"},{"furni":"bonusrare26_1*2"},{"furni":"bonusrare26_1*3"},{"furni":"bonusrare26_1*4"},{"furni":"bonusrare26_1*5"},{"credits":5,"weight":1},{"subscription":"HabboClub","subscriptionDays":3,"weight":1}]}"""
            ),
            (
                "bonusbag26_2",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"bonusrare26_2*0"},{"furni":"bonusrare26_2*1"},{"furni":"bonusrare26_2*2"},{"furni":"bonusrare26_2*3"},{"furni":"bonusrare26_2*4"},{"furni":"bonusrare26_2*5"},{"credits":5,"weight":1},{"subscription":"HabboClub","subscriptionDays":3,"weight":1}]}"""
            ),
            (
                "bonusbag26_3",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"bonusrare26_3*0"},{"furni":"bonusrare26_3*1"},{"furni":"bonusrare26_3*2"},{"furni":"bonusrare26_3*3"},{"furni":"bonusrare26_3*4"},{"furni":"bonusrare26_3*5"},{"credits":5,"weight":1},{"subscription":"HabboClub","subscriptionDays":3,"weight":1}]}"""
            ),
            ("bonusbag26_4", 3, 1, """{"target":1}"""),
            (
                "br_c25_faunacrate",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"br_c25_poisondartfrog","weight":33},{"furni":"br_c25_parrot","weight":33},{"furni":"br_c25_toucan","weight":33},{"furni":"br_c25_jaguar"}]}"""
            ),
            (
                "br_c25_floracrate",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"br_c25_lilies","weight":33},{"furni":"br_c25_orchids","weight":33},{"furni":"br_c25_passionflower","weight":33},{"furni":"br_c25_cocoatree"}]}"""
            ),
            (
                "bubblejuice_c21_crackable1",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"bubblejuice_c21_hops","also":["bubblejuice_c21_barley","bubblejuice_c21_citrus"],"weight":10},{"furni":"bubblejuice_c21_hops","also":["bubblejuice_c21_hops","bubblejuice_c21_hops"],"weight":10},{"furni":"bubblejuice_c21_barley","also":["bubblejuice_c21_barley","bubblejuice_c21_barley"],"weight":10},{"furni":"bubblejuice_c21_citrus","also":["bubblejuice_c21_citrus","bubblejuice_c21_citrus"],"weight":10},{"furni":"bubblejuice_c21_hops","also":["bubblejuice_c21_hops","bubblejuice_c21_barley","bubblejuice_c21_barley"],"weight":10},{"furni":"bubblejuice_c21_hops","also":["bubblejuice_c21_hops","bubblejuice_c21_citrus","bubblejuice_c21_citrus"],"weight":10},{"furni":"bubblejuice_c21_barley","also":["bubblejuice_c21_barley","bubblejuice_c21_citrus","bubblejuice_c21_citrus"],"weight":10},{"furni":"bubblejuice_c21_barley","also":["bubblejuice_c21_barley","bubblejuice_c21_hops","bubblejuice_c21_hops"],"weight":10},{"furni":"bubblejuice_c21_citrus","also":["bubblejuice_c21_citrus","bubblejuice_c21_hops","bubblejuice_c21_hops"],"weight":10},{"furni":"bubblejuice_c21_citrus","also":["bubblejuice_c21_citrus","bubblejuice_c21_barley","bubblejuice_c21_barley"],"weight":10}]}"""
            ),
            (
                "bubblejuice_c21_crackable2",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"bubblejuice_c21_hops","also":["bubblejuice_c21_hops","bubblejuice_c21_barley","bubblejuice_c21_barley","bubblejuice_c21_citrus","bubblejuice_c21_citrus"],"weight":40},{"furni":"bubblejuice_c21_hops","also":["bubblejuice_c21_hops","bubblejuice_c21_barley","bubblejuice_c21_barley","bubblejuice_c21_citrus","bubblejuice_c21_citrus","bubblejuice_c21_secretingredient"],"weight":30},{"furni":"bubblejuice_c21_sofa","weight":15},{"furni":"bubblejuice_c21_dartboard","weight":10},{"furni":"bubblejuice_c21_neonsign","weight":5}]}"""
            ),
            (
                "circus_c24_bluetentcrackable",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"circus_c24_cardshat","also":["circus_c24_bunnyhat","circus_c24_duckhat"],"weight":14},{"furni":"circus_c24_bunnyhat","also":["circus_c24_bunnyhat","circus_c24_cardshat"],"weight":14},{"furni":"circus_c24_cardshat","also":["circus_c24_cardshat","circus_c24_duckhat"],"weight":14},{"furni":"circus_c24_duckhat","also":["circus_c24_duckhat","circus_c24_bunnyhat"],"weight":14},{"furni":"circus_c24_cardshat","also":["circus_c24_bunnyhat","circus_c24_ball"],"weight":14},{"furni":"circus_c24_duckhat","also":["circus_c24_bunnyhat","circus_c24_ball"],"weight":14},{"furni":"circus_c24_duckhat","also":["circus_c24_cardshat","circus_c24_ball"],"weight":14},{"furni":"circus_c24_cardshat","also":["circus_c24_bunnyhat","circus_c24_duckhat","clothing_clownhat"]},{"furni":"circus_c24_cardshat","also":["circus_c24_duckhat","circus_c24_bunnyhat","clothing_clowntop"]}]}"""
            ),
            (
                "circus_c24_redtentcrackable",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"circus_c24_gymnastsgroup","weight":20},{"furni":"circus_c24_unicyclist","weight":20},{"furni":"circus_c24_acrobat","weight":20},{"furni":"circus_c24_puppyact","weight":15},{"furni":"circus_c24_mouseact","weight":15},{"furni":"circus_c24_ponyact","weight":10}]}"""
            ),
            (
                "diamond_c21_giftbox",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"clothing_diahermeshat","weight":10},{"furni":"clothing_diaelegantcrown","weight":20},{"furni":"exe_c15_telephone","weight":100},{"furni":"tokyo_c18_magazinerack","weight":90},{"furni":"hygge_c18_stove","weight":90},{"furni":"bling_shwr","weight":90},{"furni":"band_c19_drums","weight":90},{"furni":"attic15_carpet","weight":90},{"furni":"clothing_nutrainers","weight":75},{"furni":"clothing_denimshorts","weight":75},{"furni":"clothing_leathertrousers","weight":75},{"furni":"clothing_chestbag","weight":75},{"furni":"clothing_grandetail","weight":70}]}"""
            ),
            (
                "diamond_c22_giftbox",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"clothing_diafeathercrown","weight":10},{"furni":"clothing_diaturban","weight":20},{"furni":"clothing_diahalo","weight":50},{"furni":"rainyday_c20_paintset","weight":100},{"furni":"bling_toilet","weight":90},{"furni":"olympics_c16_treadmill","weight":90},{"furni":"js_jetski2","weight":90},{"furni":"antique_c21_armchair","weight":90},{"furni":"clothing_elegantponytail","weight":70},{"furni":"clothing_pompomhat","weight":75},{"furni":"clothing_leatherhoodie","weight":75},{"furni":"clothing_beetshirt","weight":75},{"furni":"clothing_sportsshade","weight":75}]}"""
            ),
            (
                "diamond_c25_giftbox4",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"clothing_diasparkleparty","weight":10},{"furni":"clothing_diaplume","weight":20},{"furni":"clothing_diastar","weight":50},{"furni":"easter_c17_sprinkler","weight":100},{"furni":"easter_c24_bed","weight":90},{"furni":"nyc_c23_wallposters","weight":90},{"furni":"santorini_c17_donkey","weight":90},{"furni":"easter_c22_tree","weight":90},{"furni":"easter_c19_logtable","weight":90},{"furni":"clothing_plaitedbunhair","weight":70},{"furni":"clothing_animalprint","weight":75},{"furni":"clothing_gardenapron","weight":75},{"furni":"clothing_satchel","weight":75},{"furni":"rainyday_c20_retrogames","weight":75}]}"""
            ),
            (
                "dino_c22_fossilrock",
                3,
                1,
                """{"target":1,"requiredEffectIds":[182,183],"rewards":[{"furni":"dino_c22_bigfoot"},{"furni":"dino_c22_bigteeth"},{"furni":"dino_c22_bonyplate"},{"furni":"dino_c22_clawedfoot"},{"furni":"dino_c22_flipper"},{"furni":"dino_c22_smallteeth"}]}"""
            ),
            (
                "disco_c26_discoball",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"disco_c26_walkman","also":["disco_c26_helmet","disco_c26_wheels"]},{"furni":"disco_c26_walkman","also":["disco_c26_lightstick","disco_c26_tool"]},{"furni":"disco_c26_walkman","also":["disco_c26_heartglitter","disco_c26_candyheart"]},{"furni":"disco_c26_helmet","also":["disco_c26_starglitter","disco_c26_lightstick"]},{"furni":"disco_c26_helmet","also":["disco_c26_wheels","disco_c26_tool"]},{"furni":"disco_c26_candyheart","also":["disco_c26_lightstick","disco_c26_tool"]},{"furni":"disco_c26_candyheart","also":["disco_c26_heartglitter","disco_c26_wheels"]},{"furni":"disco_c26_heartglitter","also":["disco_c26_starglitter","disco_c26_starglitter"]}]}"""
            ),
            (
                "dream_c24_dreammirror",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"dream_c24_moonshard","also":["dream_c24_moonshard","dream_c24_cloudplant"]},{"furni":"dream_c24_moonshard","also":["dream_c24_puddle","dream_c24_puddle"]},{"furni":"dream_c24_tinyrainbow","also":["dream_c24_cloudplant","dream_c24_cloudplant"]},{"furni":"dream_c24_tinyrainbow","also":["dream_c24_cloudplant","dream_c24_puddle"]},{"furni":"dream_c24_tinyrainbow","also":["dream_c24_cloudplant","dream_c24_moonshard"]},{"furni":"dream_c24_tinyrainbow","also":["dream_c24_puddle","dream_c24_moonshard"]},{"furni":"dream_c24_tinyrainbow","also":["dream_c24_tinyrainbow","dream_c24_puddle"]},{"furni":"dream_c24_tinyrainbow","also":["dream_c24_tinyrainbow","dream_c24_tinyrainbow"]}]}"""
            ),
            (
                "dream_c24_storybook",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"dream_c24_storyboat","also":["dream_c24_storyboat","dream_c24_storyboat"]},{"furni":"dream_c24_storyplane","also":["dream_c24_storyplane","dream_c24_storyplane"]},{"furni":"dream_c24_storyswan","also":["dream_c24_storyswan","dream_c24_storyswan"]},{"furni":"dream_c24_storybookpages","also":["dream_c24_storybookpages","dream_c24_storybookpages"]},{"furni":"dream_c24_storyboat","also":["dream_c24_storyboat","dream_c24_storyplane"]},{"furni":"dream_c24_storyswan","also":["dream_c24_storyswan","dream_c24_storybookpages"]},{"furni":"dream_c24_storybookpages","also":["dream_c24_storybookpages","dream_c24_storyplane"]},{"furni":"dream_c24_storyboat","also":["dream_c24_storyplane","dream_c24_storyswan"]}]}"""
            ),
            (
                "easter_c22_aerialbugs1",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"easter_c22_morpho1","also":["easter_c22_agrias1","easter_c22_dragonfly1"]}]}"""
            ),
            (
                "easter_c22_aerialbugs2",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"easter_c22_morpho2","also":["easter_c22_agrias2","easter_c22_dragonfly2"]}]}"""
            ),
            (
                "easter_c22_apparelbag",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"clothing_ladybirdbag","weight":45},{"furni":"clothing_butterflyhair","weight":45},{"furni":"clothing_snailfriend","weight":10}]}"""
            ),
            (
                "easter_c22_bugkit",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"easter_c22_apparelbag"},{"furni":"easter_c22_groundbugs1","weight":33},{"furni":"easter_c22_groundbugs3","weight":33},{"furni":"easter_c22_aerialbugs1","weight":33}]}"""
            ),
            (
                "easter_c22_deluxebugkit",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"easter_c22_groundbugs2","also":["easter_c22_apparelbag"]},{"furni":"easter_c22_groundbugs4","also":["easter_c22_apparelbag"]},{"furni":"easter_c22_aerialbugs2","also":["easter_c22_apparelbag"]}]}"""
            ),
            (
                "easter_c22_groundbugs1",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"easter_c22_scarab1","also":["easter_c22_ladybird1","easter_c22_sawstagbeetle1"]}]}"""
            ),
            (
                "easter_c22_groundbugs2",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"easter_c22_scarab2","also":["easter_c22_ladybird2","easter_c22_sawstagbeetle2"]}]}"""
            ),
            (
                "easter_c22_groundbugs3",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"easter_c22_mantis1","also":["easter_c22_goliathbeetle1","easter_c22_caterpillar1"]}]}"""
            ),
            (
                "easter_c22_groundbugs4",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"easter_c22_mantis2","also":["easter_c22_goliathbeetle2","easter_c22_caterpillar2"]}]}"""
            ),
            ("easter_c23_craftbotcrackable", 9, 1, """{"target":8}"""),
            (
                "easter_c23_recylingbin",
                3,
                1,
                """{"target":1,"requiredEffectId":137,"rewardPlacement":"Inventory","rewards":[{"furni":"clothing_trash","weight":10},{"furni":"easter_c23_pileofclothes","also":["easter_c23_pileofmixedfood","easter_c23_pileofoldtech"],"weight":9},{"furni":"easter_c23_pileofclothes","also":["easter_c23_pileofclothes","easter_c23_pileofclothes"],"weight":9},{"furni":"easter_c23_pileofmixedfood","also":["easter_c23_pileofmixedfood","easter_c23_pileofmixedfood"],"weight":9},{"furni":"easter_c23_pileofoldtech","also":["easter_c23_pileofoldtech","easter_c23_pileofoldtech"],"weight":9},{"furni":"easter_c23_pileofclothes","also":["easter_c23_pileofclothes","easter_c23_pileofmixedfood"],"weight":9},{"furni":"easter_c23_pileofmixedfood","also":["easter_c23_pileofmixedfood","easter_c23_pileofoldtech"],"weight":9},{"furni":"easter_c23_pileofoldtech","also":["easter_c23_pileofoldtech","easter_c23_pileofclothes"],"weight":9},{"furni":"easter_c23_pileofclothes","also":["easter_c23_pileofclothes","easter_c23_pileofoldtech"],"weight":9},{"furni":"easter_c23_pileofmixedfood","also":["easter_c23_pileofmixedfood","easter_c23_pileofclothes"],"weight":9},{"furni":"easter_c23_pileofoldtech","also":["easter_c23_pileofoldtech","easter_c23_pileofmixedfood"],"weight":9}]}"""
            ),
            (
                "easter_c23_solarbox",
                3,
                1,
                """{"target":1,"requiredEffectId":137,"rewards":[{"furni":"easter_c23_solarenergy","weight":10},{"furni":"easter_c23_bigbattery","weight":30},{"furni":"easter_c23_battery","weight":60}]}"""
            ),
            (
                "easter_c24_airseed",
                5,
                1,
                """{"target":4,"requiredEffectId":6,"rewards":[{"furni":"easter_c24_airfruit","weight":95},{"furni":"easter_c24_shinyairfruit","weight":5}]}"""
            ),
            (
                "easter_c24_darkseed",
                5,
                1,
                """{"target":4,"requiredEffectId":180,"rewards":[{"furni":"easter_c24_darkfruit","weight":95},{"furni":"easter_c24_shinydarkfruit","weight":5}]}"""
            ),
            (
                "easter_c24_earthseed",
                5,
                1,
                """{"target":4,"rewards":[{"furni":"easter_c24_earthfruit","weight":95},{"furni":"easter_c24_shinyearthfruit","weight":5}]}"""
            ),
            (
                "easter_c24_elementalseed",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"easter_c24_airseed"},{"furni":"easter_c24_earthseed"},{"furni":"easter_c24_fireseed"},{"furni":"easter_c24_waterseed"}]}"""
            ),
            (
                "easter_c24_fairyseed",
                5,
                1,
                """{"target":4,"requiredEffectId":186,"rewards":[{"furni":"easter_c24_fairyfruit","weight":95},{"furni":"easter_c24_shinyfairyfruit","weight":5}]}"""
            ),
            (
                "easter_c24_fireseed",
                5,
                1,
                """{"target":4,"requiredEffectId":5,"rewards":[{"furni":"easter_c24_firefruit","weight":95},{"furni":"easter_c24_shinyfirefruit","weight":5}]}"""
            ),
            (
                "easter_c24_lightseed",
                5,
                1,
                """{"target":4,"requiredEffectId":137,"rewards":[{"furni":"easter_c24_lightfruit","weight":95},{"furni":"easter_c24_shinylightfruit","weight":5}]}"""
            ),
            (
                "easter_c24_rainbowseed",
                5,
                1,
                """{"target":4,"requiredEffectId":7,"rewards":[{"furni":"easter_c24_rainbowfruit","weight":95},{"furni":"easter_c24_shinyrainbowfruit","weight":5}]}"""
            ),
            (
                "easter_c24_waterseed",
                5,
                1,
                """{"target":4,"requiredEffectId":192,"rewards":[{"furni":"easter_c24_waterfruit","weight":95},{"furni":"easter_c24_shinywaterfruit","weight":5}]}"""
            ),
            (
                "easter_c25_designerbag",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"easter_c25_blueprint1","also":["easter_c25_blueprint3","easter_c25_craftingtools"],"weight":40},{"furni":"easter_c25_blueprint3","also":["easter_c25_blueprint3","easter_c25_blueprint3"],"weight":20},{"furni":"easter_c25_blueprint1","also":["easter_c25_blueprint1","easter_c25_blueprint1"],"weight":20},{"furni":"easter_c25_craftingtools","also":["easter_c25_craftingtools","easter_c25_craftingtools"],"weight":20}]}"""
            ),
            (
                "easter_c25_designerbag2",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"easter_c25_blueprint4","also":["easter_c25_blueprint2","easter_c25_hairgel"],"weight":40},{"furni":"easter_c25_blueprint2","also":["easter_c25_blueprint2","easter_c25_blueprint2"],"weight":20},{"furni":"easter_c25_blueprint4","also":["easter_c25_blueprint4","easter_c25_blueprint4"],"weight":20},{"furni":"easter_c25_hairgel","also":["easter_c25_hairgel","easter_c25_hairgel"],"weight":20}]}"""
            ),
            (
                "easter_c26_elvenbox",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"easter_c26_elvenegg1","also":["easter_c26_elvenegg1","easter_c26_elvenorganicmat"]},{"furni":"easter_c26_elvenegg2","also":["easter_c26_elvenegg2","easter_c26_elvenorganicmat"]},{"furni":"easter_c26_elvenegg4","also":["easter_c26_elvenegg4","easter_c26_elvencloth"]},{"furni":"easter_c26_elvenegg3","also":["easter_c26_elvenegg3","easter_c26_elvencloth"]},{"furni":"easter_c26_elvenegg1","also":["easter_c26_elvenegg3","easter_c26_elvenegg2"]},{"furni":"easter_c26_elvenegg4","also":["easter_c26_elvencloth","easter_c26_elvenorganicmat"]}]}"""
            ),
            (
                "fall_c23_deluxebasket",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"fall_c23_campfire","also":["fall_c23_phonecam","fall_c23_picnicblanket","clothing_habbobeanie"],"weight":12},{"furni":"fall_c23_campfire","also":["clothing_fluffyjacket","clothing_habbobeanie","fall_c23_leafpile"],"weight":26},{"furni":"fall_c23_phonecam","also":["clothing_pinaforedress","clothing_docfranks","fall_c23_leafcurtains"],"weight":26},{"furni":"fall_c23_picnicblanket","also":["fall_c23_shiba","clothing_knittedbunnybeanie","fall_c23_leafyfloor"],"weight":26},{"furni":"fall_c23_shiba","also":["fall_c23_samoyed","clothing_fluffyhat","clothing_docfranks"],"weight":5},{"furni":"clothing_fluffyjacket","also":["fall_c23_samoyed","clothing_fluffyhat","clothing_docfranks"],"weight":5}]}"""
            ),
            (
                "fall_c23_picnicbasket",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"fall_c23_leafpile","also":["fall_c23_leafyfloor","fall_c23_leafcurtains"],"weight":12},{"furni":"fall_c23_leafpile","also":["fall_c23_picnicblanket","clothing_knittedbunnybeanie"],"weight":26},{"furni":"clothing_habbobeanie","also":["fall_c23_phonecam","fall_c23_leafcurtains"],"weight":26},{"furni":"fall_c23_campfire","also":["fall_c23_leafyfloor","clothing_pinaforedress"],"weight":26},{"furni":"fall_c23_leafpile","also":["fall_c23_leafyfloor","fall_c23_shiba","fall_c23_leafcurtains"],"weight":5},{"furni":"fall_c23_leafpile","also":["fall_c23_leafyfloor","clothing_fluffyjacket","fall_c23_leafcurtains"],"weight":5}]}"""
            ),
            (
                "fantasy_c22_treasure1",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"fantasy_c22_metal","also":["fantasy_c22_metal","fantasy_c22_metal","fantasy_c22_bluepotion"]},{"furni":"fantasy_c22_wood","also":["fantasy_c22_wood","fantasy_c22_wood","fantasy_c22_greenpotion"]},{"furni":"fantasy_c22_cloth","also":["fantasy_c22_cloth","fantasy_c22_cloth","fantasy_c22_bluepotion"]},{"furni":"fantasy_c22_metal","also":["fantasy_c22_wood","fantasy_c22_cloth","fantasy_c22_greenpotion"]},{"furni":"fantasy_c22_metal","also":["fantasy_c22_metal","fantasy_c22_cloth","fantasy_c22_bluepotion"]},{"furni":"fantasy_c22_wood","also":["fantasy_c22_wood","fantasy_c22_metal","fantasy_c22_greenpotion"]},{"furni":"fantasy_c22_cloth","also":["fantasy_c22_cloth","fantasy_c22_wood","fantasy_c22_bluepotion"]},{"furni":"fantasy_c22_metal","also":["fantasy_c22_metal","fantasy_c22_wood","fantasy_c22_greenpotion"]},{"furni":"fantasy_c22_wood","also":["fantasy_c22_wood","fantasy_c22_cloth","fantasy_c22_redpotion"]},{"furni":"fantasy_c22_cloth","also":["fantasy_c22_cloth","fantasy_c22_metal","fantasy_c22_redpotion"]}]}"""
            ),
            (
                "fantasy_c22_treasure2",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"fantasy_c22_bluepotion","also":["fantasy_c22_bluepotion","fantasy_c22_bluepotion","fantasy_c22_rune"]},{"furni":"fantasy_c22_greenpotion","also":["fantasy_c22_greenpotion","fantasy_c22_greenpotion","fantasy_c22_coins"]},{"furni":"fantasy_c22_redpotion","also":["fantasy_c22_redpotion","fantasy_c22_redpotion","fantasy_c22_rune"]},{"furni":"fantasy_c22_bluepotion","also":["fantasy_c22_greenpotion","fantasy_c22_redpotion","fantasy_c22_coins"]},{"furni":"fantasy_c22_bluepotion","also":["fantasy_c22_bluepotion","fantasy_c22_redpotion","fantasy_c22_rune"]},{"furni":"fantasy_c22_greenpotion","also":["fantasy_c22_greenpotion","fantasy_c22_bluepotion","fantasy_c22_coins"]},{"furni":"fantasy_c22_redpotion","also":["fantasy_c22_redpotion","fantasy_c22_greenpotion","fantasy_c22_rune"]},{"furni":"fantasy_c22_bluepotion","also":["fantasy_c22_bluepotion","fantasy_c22_greenpotion","fantasy_c22_coins"]},{"furni":"fantasy_c22_greenpotion","also":["fantasy_c22_greenpotion","fantasy_c22_redpotion","fantasy_c22_crystal"]},{"furni":"fantasy_c22_redpotion","also":["fantasy_c22_redpotion","fantasy_c22_bluepotion","fantasy_c22_crystal"]}]}"""
            ),
            (
                "gacha_c25_gachamachine",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"gacha_c25_tiger"},{"furni":"gacha_c25_duck"},{"furni":"gacha_c25_octopus"},{"furni":"gacha_c25_sheep"},{"furni":"gacha_c25_hyena"},{"furni":"gacha_c25_owl"}]}"""
            ),
            (
                "gacha_c25_royalgacha",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"gacha_c25_royaltiger"},{"furni":"gacha_c25_royalduck"},{"furni":"gacha_c25_royaloctopus"},{"furni":"gacha_c25_royalsheep"},{"furni":"gacha_c25_royalhyena"},{"furni":"gacha_c25_royalowl"}]}"""
            ),
            (
                "giftbox_c25_crackable1",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"clothing_bunnyeyepatch","weight":5},{"furni":"clothing_bunnyface","weight":5},{"furni":"clothing_fashionsunglasses","weight":5},{"furni":"clothing_bunnyearrings","weight":5},{"furni":"clothing_thinscarf","weight":5},{"furni":"easter_c19_turnipbuddies","weight":10},{"furni":"easter_c22_barrelcactus","weight":15},{"furni":"easter_c19_meadow","weight":10},{"furni":"easter_c18_dragonflies","weight":10},{"furni":"easter_c20_heather","weight":10},{"furni":"easter_c17_appletree","weight":10}]}"""
            ),
            (
                "giftbox_c25_crackable2",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"clothing_survivalbackpack","weight":10},{"furni":"clothing_zebratop","weight":10},{"furni":"clothing_backcap","weight":10},{"furni":"clothing_sportsshade","weight":10},{"furni":"tent_camo","weight":10},{"furni":"army_c15_compass","weight":10},{"furni":"xmas14_hammock","weight":10},{"furni":"jungle_c16_tele","weight":5},{"furni":"clothing_sunburntface","weight":5},{"furni":"clothing_brnecklace","weight":5}]}"""
            ),
            (
                "giftbox_c25_crackable3",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"tiki_waterfall","weight":4},{"furni":"bw_shower","weight":14},{"furni":"coco_divan_c3","weight":14},{"furni":"st_palooza_balloons","weight":2},{"furni":"clothing_discohead","weight":8},{"furni":"jetset_tent","weight":14},{"furni":"clothing_armfloats","weight":8},{"furni":"xmas14_recliner","weight":14},{"furni":"fest_c19_coalicecream","weight":8},{"furni":"hblooza_icecream","weight":2},{"furni":"anc_sun","weight":4},{"furni":"paris_c15_parasol","weight":8}]}"""
            ),
            ("giftbox_c25_crackable4", 3, 1, """{"target":1}"""),
            (
                "giftbox_c25_crackable5",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"xmas_c25_penguin1","weight":16},{"furni":"xmas_c25_penguin2","weight":15},{"furni":"xmas_c25_penguin3","weight":13},{"furni":"xmas_c25_penguin4","weight":13},{"furni":"xmas_c25_penguin5","weight":12},{"furni":"xmas_c25_penguin6","weight":11},{"furni":"xmas_c25_penguin7","weight":11},{"furni":"xmas_c25_penguin8","weight":10}]}"""
            ),
            ("giftbox_c25_crackable6", 3, 1, """{"target":1}"""),
            (
                "giftbox_c25_crackable7",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"clothing_survivalbackpack","weight":16},{"furni":"easter_c20_campingessentials","weight":16},{"furni":"army_c15_bed","weight":12},{"furni":"clothing_nosebandage","weight":10},{"furni":"clothing_cheekbandage","weight":10},{"furni":"clothing_bandagedtorso","weight":8},{"furni":"clothing_bandagedhead","weight":8},{"furni":"tent_blue","weight":6},{"furni":"tent_orange","weight":6},{"furni":"clothing_respirator","weight":5},{"furni":"clothing_mouldytoastbackpack","weight":3}]}"""
            ),
            (
                "graffiti_c24_spraypaints",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"graffiti_c24_tealspray","also":["graffiti_c24_tealspray","graffiti_c24_tealspray","graffiti_c24_bluespray"]},{"furni":"graffiti_c24_bluespray","also":["graffiti_c24_bluespray","graffiti_c24_redspray","graffiti_c24_pinkspray"]},{"furni":"graffiti_c24_pinkspray","also":["graffiti_c24_pinkspray","graffiti_c24_yellowspray","graffiti_c24_yellowspray"]},{"furni":"graffiti_c24_bluespray","also":["graffiti_c24_redspray","graffiti_c24_yellowspray","graffiti_c24_yellowspray"]},{"furni":"graffiti_c24_tealspray","also":["graffiti_c24_yellowspray","graffiti_c24_redspray","graffiti_c24_redspray"]},{"furni":"graffiti_c24_pinkspray","also":["graffiti_c24_pinkspray","graffiti_c24_bluespray","graffiti_c24_yellowspray"]},{"furni":"graffiti_c24_tealspray","also":["graffiti_c24_tealspray","graffiti_c24_pinkspray","graffiti_c24_redspray"]},{"furni":"graffiti_c24_bluespray","also":["graffiti_c24_bluespray","graffiti_c24_yellowspray","graffiti_c24_pinkspray"]}]}"""
            ),
            (
                "graffiti_c24_tv",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"graffiti_c24_gloves","also":["graffiti_c24_gloves","graffiti_c24_bricks","graffiti_c24_bricks"],"weight":142},{"furni":"graffiti_c24_gloves","also":["graffiti_c24_gloves","graffiti_c24_flashlight","graffiti_c24_bricks"],"weight":284},{"furni":"graffiti_c24_gloves","also":["graffiti_c24_bricks","graffiti_c24_flashlight","graffiti_c24_flashlight"],"weight":142},{"furni":"clothing_splattermask","also":["graffiti_c24_bricks","graffiti_c24_flashlight","graffiti_c24_flashlight"],"weight":142},{"furni":"clothing_splattermask","also":["graffiti_c24_gloves","graffiti_c24_flashlight","graffiti_c24_flashlight"],"weight":142},{"furni":"clothing_splattermask","also":["clothing_splattermask","graffiti_c24_bricks","graffiti_c24_bricks"],"weight":142}]}"""
            ),
            (
                "habbo25_c25_bdayballoon",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"uni_c23_bubblejuicepong","weight":140},{"furni":"clothing_megaoversizedtshirt","weight":140},{"furni":"fest_c19_falafelstall","weight":120},{"furni":"vwave_c21_frenchbulldog","weight":120},{"furni":"clothing_balloonpigtails","weight":120},{"furni":"fest_c19_loverstent","weight":100},{"furni":"clothing_retrosuit","weight":100},{"furni":"clothing_poolpartyshades","weight":60},{"furni":"clothing_catfloat","weight":60},{"furni":"habbo25_c25_bdayballoon","weight":36},{"furni":"habbo25_c25_bdayballoon2","weight":4}]}"""
            ),
            (
                "habbo25_c25_bdayballoon2",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"barrier*4","weight":13},{"furni":"minirare_sleepingbag*10","weight":13},{"furni":"minirare_scifirocket*1","weight":11},{"furni":"minirare_elephant_statue*4","weight":10},{"furni":"minirare_pillow*9","weight":10},{"furni":"minirare_dragonlamp*0","weight":9},{"furni":"scifiport*11","weight":8},{"furni":"rare_fountain*7","weight":8},{"furni":"rare_parasol*5","weight":7},{"furni":"rare_fan*11","weight":7},{"furni":"rare_icecream*12","weight":4}]}"""
            ),
            (
                "hhistory_c24_goldtimecapsule",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"hhistory_c24_megasoap","also":["clothing_cargopants","hhistory_c24_pupchi1","hhistory_c24_cactus"]},{"furni":"hhistory_c24_megapopsicle","also":["hhistory_c24_megasushi","hhistory_c24_indestructiblephone","clothing_frostedtipshair"]},{"furni":"hhistory_c24_megajazztape","also":["hhistory_c24_megahorse","clothing_butterflycliphair","hhistory_c24_fluffby1"]},{"furni":"hhistory_c24_cheep","also":["hhistory_c24_megaflower","clothing_couturetracksuit","hhistory_c24_fluffby2"]},{"furni":"clothing_cargopants","also":["hhistory_c24_megaring","hhistory_c24_pupchi2","hhistory_c24_fluffby3"]},{"furni":"hhistory_c24_megapencil","also":["hhistory_c24_lavalamp4","clothing_frostedtipshair","hhistory_c24_fluffby4"]},{"furni":"hhistory_c24_8bittrip","also":["hhistory_c24_lavalamp5","clothing_fluffybuckethat","hhistory_c24_fluffby5"]},{"furni":"hhistory_c24_megamooncake","also":["hhistory_c24_lavalamp6","clothing_digipetnecklace","hhistory_c24_fluffby6"]}]}"""
            ),
            (
                "hhistory_c24_silvertimecapsule",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"hhistory_c24_megapencil","also":["hhistory_c24_megajazztape","hhistory_c24_cactus","hhistory_c24_lavalamp1"],"weight":12375},{"furni":"hhistory_c24_megapopsicle","also":["hhistory_c24_cheep","hhistory_c24_8bittrip","hhistory_c24_lavalamp2"],"weight":12375},{"furni":"hhistory_c24_megamooncake","also":["hhistory_c24_megasoap","hhistory_c24_megahorse","hhistory_c24_lavalamp3"],"weight":12375},{"furni":"hhistory_c24_megasushi","also":["hhistory_c24_megaflower","hhistory_c24_megaring"],"weight":12375},{"furni":"hhistory_c24_megasoap","also":["hhistory_c24_megaring","hhistory_c24_cactus"],"weight":12375},{"furni":"hhistory_c24_megapopsicle","also":["hhistory_c24_megasushi","hhistory_c24_megapencil"],"weight":12375},{"furni":"hhistory_c24_megajazztape","also":["hhistory_c24_megahorse","hhistory_c24_8bittrip"],"weight":12375},{"furni":"hhistory_c24_megamooncake","also":["hhistory_c24_cheep","hhistory_c24_megaflower"],"weight":12375},{"furni":"hhistory_c24_goldtimecapsule","weight":1000}]}"""
            ),
            (
                "hobbies_c26_boardgamescrackable",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"hobbies_c26_d4","also":["hobbies_c26_chair","hobbies_c26_chair"],"weight":15},{"furni":"hobbies_c26_d6","also":["hobbies_c26_dicetray","hobbies_c26_journal"],"weight":10},{"furni":"hobbies_c26_d8","also":["hobbies_c26_dmscreen","hobbies_c26_dicetray"],"weight":10},{"furni":"hobbies_c26_d10","also":["hobbies_c26_chair","hobbies_c26_journal"],"weight":10},{"furni":"hobbies_c26_d12","also":["hobbies_c26_gamingtable"],"weight":10},{"furni":"hobbies_c26_d20","also":["hobbies_c26_owlbear"],"weight":5},{"furni":"hobbies_c26_d4","also":["hobbies_c26_d6","hobbies_c26_d8","hobbies_c26_d10","hobbies_c26_d12","hobbies_c26_d20","clothing_fantasydemon"],"weight":5},{"furni":"hobbies_c26_ornated4","also":["hobbies_c26_chair","hobbies_c26_chair"],"weight":5},{"furni":"hobbies_c26_ornated6","also":["hobbies_c26_dicetray","hobbies_c26_journal"],"weight":5},{"furni":"hobbies_c26_ornated8","also":["hobbies_c26_dmscreen","hobbies_c26_dicetray"],"weight":5},{"furni":"hobbies_c26_ornated10","also":["hobbies_c26_chair","hobbies_c26_journal"],"weight":5},{"furni":"hobbies_c26_ornated12","also":["hobbies_c26_gamingtable"],"weight":5},{"furni":"hobbies_c26_d4","also":["hobbies_c26_d6","hobbies_c26_d8","hobbies_c26_d10","hobbies_c26_d12","hobbies_c26_d20"],"weight":4},{"furni":"hobbies_c26_ornated20","also":["hobbies_c26_owlbear"],"weight":3},{"furni":"hobbies_c26_ornated4","also":["hobbies_c26_ornated6","hobbies_c26_ornated8","hobbies_c26_ornated10","hobbies_c26_ornated12","hobbies_c26_ornated20","clothing_crownedfantasydemon"],"weight":2},{"furni":"hobbies_c26_ornated4","also":["hobbies_c26_ornated6","hobbies_c26_ornated8","hobbies_c26_ornated10","hobbies_c26_ornated12","hobbies_c26_ornated20"]}]}"""
            ),
            (
                "hobbies_c26_gardeningcrackable",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"hobbies_c26_wateringcan","also":["hobbies_c26_rose","hobbies_c26_gloves"],"weight":15},{"furni":"hobbies_c26_tool3","also":["hobbies_c26_flower","hobbies_c26_flowerpot1"],"weight":15},{"furni":"hobbies_c26_tool2","also":["hobbies_c26_rose","hobbies_c26_flowerpot2"],"weight":15},{"furni":"hobbies_c26_tool1","also":["hobbies_c26_flower","hobbies_c26_flowerpot1"],"weight":15},{"furni":"hobbies_c26_shovel","also":["hobbies_c26_dirtpile","hobbies_c26_flowerpot2"],"weight":15},{"furni":"hobbies_c26_birdfeeder","also":["hobbies_c26_wheelbarrow","hobbies_c26_dirtpile"],"weight":10},{"furni":"hobbies_c26_lawnmover","also":["hobbies_c26_waterhose","hobbies_c26_gloves"],"weight":10},{"furni":"hobbies_c26_preciouswateringcan","weight":5}]}"""
            ),
            (
                "hobbies_c26_preciouswateringcan",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"clothing_flowereye"},{"furni":"clothing_flowerheart"}]}"""
            ),
            (
                "hobbies_c26_sewingcrackable",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"hobbies_c26_hotgluegun","also":["hobbies_c26_buttons","hobbies_c26_fabricscissors","hobbies_c26_tapemeasure"],"weight":25},{"furni":"hobbies_c26_teddypincushion","also":["hobbies_c26_buttons","hobbies_c26_threads","hobbies_c26_fabricscissors"],"weight":25},{"furni":"hobbies_c26_tapemeasure","also":["hobbies_c26_threads","hobbies_c26_pincushion","hobbies_c26_mannequin"],"weight":15},{"furni":"hobbies_c26_sewingmachine","also":["hobbies_c26_threads","hobbies_c26_teddypincushion","hobbies_c26_buttons"],"weight":15},{"furni":"hobbies_c26_sewingmachine","also":["hobbies_c26_loosetags","hobbies_c26_mannequin","hobbies_c26_hotgluegun"],"weight":15},{"furni":"hobbies_c26_teddypincushion","also":["hobbies_c26_loosetags","clothing_snakeyscarf"],"weight":3},{"furni":"hobbies_c26_loosetags","also":["clothing_snakeyscarf","clothing_diykittyplush"],"weight":2}]}"""
            ),
            (
                "hween_c22_archdarkangel",
                23,
                1,
                """{"target":22,"requiredEffectId":162,"rewards":[{"furni":"clothing_gothiccoat"},{"furni":"clothing_gothichat"},{"furni":"clothing_gothicflowerhorns"},{"furni":"clothing_gothicdress"}]}"""
            ),
            (
                "hween_c22_darkangel",
                23,
                1,
                """{"target":22,"requiredEffectId":5,"rewardPlacement":"Inventory","rewards":[{"furni":"hween_c22_darkcandles","also":["hween_c22_darkcandles","hween_c22_darkcandles"]},{"furni":"hween_c22_roseskull","also":["hween_c22_roseskull","hween_c22_roseskull"]},{"furni":"hween_c22_darkfeathers","also":["hween_c22_darkfeathers","hween_c22_darkfeathers"]},{"furni":"hween_c22_darkskull","also":["hween_c22_darkskull","hween_c22_darkskull"]},{"furni":"hween_c22_darkcandles","also":["hween_c22_darkcandles","hween_c22_roseskull"]},{"furni":"hween_c22_roseskull","also":["hween_c22_roseskull","hween_c22_darkfeathers"]},{"furni":"hween_c22_darkfeathers","also":["hween_c22_darkfeathers","hween_c22_darkskull"]},{"furni":"hween_c22_darkskull","also":["hween_c22_darkskull","hween_c22_darkcandles"]},{"furni":"hween_c22_darkcandles","also":["hween_c22_roseskull","hween_c22_darkfeathers"]},{"furni":"hween_c22_roseskull","also":["hween_c22_darkfeathers","hween_c22_darkskull"]},{"furni":"hween_c22_darkfeathers","also":["hween_c22_darkskull","hween_c22_darkcandles"]},{"furni":"hween_c22_darkskull","also":["hween_c22_darkcandles","hween_c22_roseskull"]}]}"""
            ),
            (
                "hween_c22_darkangelstatue",
                3,
                1,
                """{"target":1,"requiredEffectId":5,"rewards":[{"furni":"hween_c22_darkangel","weight":95},{"furni":"hween_c22_archdarkangel","weight":5}]}"""
            ),
            (
                "hween_c23_isischest",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"hween_c23_isisjar1"},{"furni":"hween_c23_isisjar2"},{"furni":"hween_c23_isisjar3"},{"furni":"hween_c23_isisjar4"}]}"""
            ),
            (
                "hween_c23_osirischest",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"hween_c23_osirisjar1"},{"furni":"hween_c23_osirisjar2"},{"furni":"hween_c23_osirisjar3"},{"furni":"hween_c23_osirisjar4"}]}"""
            ),
            (
                "hween_c23_rachest",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"hween_c23_rajar1"},{"furni":"hween_c23_rajar2"},{"furni":"hween_c23_rajar3"},{"furni":"hween_c23_rajar4"}]}"""
            ),
            (
                "hween_c23_seth",
                23,
                1,
                """{"target":22,"requiredEffectId":162,"rewards":[{"furni":"hween_c23_osirischest"},{"furni":"hween_c23_isischest"},{"furni":"hween_c23_rachest"}]}"""
            ),
            ("hween_c23_seth3", 23, 2, """{"target":22,"rewardTo":"Cracker"}"""),
            (
                "hween_c24_craftbox",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"hween_c24_blueprints","weight":40},{"furni":"hween_c24_paintbrushes","weight":40},{"furni":"hween_c24_pens","weight":40},{"furni":"hween_c24_blueprints","also":["hween_c24_blueprints","hween_c24_blueprints"],"weight":60},{"furni":"hween_c24_paintbrushes","also":["hween_c24_paintbrushes","hween_c24_paintbrushes"],"weight":60},{"furni":"hween_c24_pens","also":["hween_c24_pens","hween_c24_pens"],"weight":60}]}"""
            ),
            (
                "hween_c24_neonmixer",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"hween_c24_yellowpaint","weight":40},{"furni":"hween_c24_bluepaint","weight":40},{"furni":"hween_c24_pinkpaint","weight":40},{"furni":"hween_c24_pinkpaint","also":["hween_c24_pinkpaint","hween_c24_pinkpaint"],"weight":60},{"furni":"hween_c24_bluepaint","also":["hween_c24_bluepaint","hween_c24_bluepaint"],"weight":60},{"furni":"hween_c24_yellowpaint","also":["hween_c24_yellowpaint","hween_c24_yellowpaint"],"weight":60}]}"""
            ),
            (
                "hween_c25_infected1",
                23,
                1,
                """{"target":22,"rewardPlacement":"Inventory","rewards":[{"furni":"hween_c25_infected2","weight":25},{"furni":"hween_c25_scrapfabric","also":["hween_c25_scrapfabric","hween_c25_scrapfabric"],"weight":25},{"furni":"hween_c25_scrapwood","also":["hween_c25_scrapwood","hween_c25_scrapwood"],"weight":25},{"furni":"hween_c25_scrapmetal","also":["hween_c25_scrapmetal","hween_c25_scrapmetal"],"weight":25},{"furni":"hween_c25_scrapfabric","also":["hween_c25_scrapwood","hween_c25_scrapmetal"],"weight":25}]}"""
            ),
            (
                "hween_c25_infected2",
                23,
                1,
                """{"target":22,"rewardPlacement":"Inventory","rewards":[{"furni":"hween_c25_infected3","weight":25},{"furni":"hween_c25_scrapclothing","also":["hween_c25_scrapclothing","hween_c25_scrapclothing"],"weight":25},{"furni":"hween_c25_tools","also":["hween_c25_tools","hween_c25_tools"],"weight":25},{"furni":"hween_c25_rope","also":["hween_c25_rope","hween_c25_rope"],"weight":25},{"furni":"hween_c25_scrapclothing","also":["hween_c25_tools","hween_c25_rope"],"weight":25}]}"""
            ),
            (
                "hween_c25_infected3",
                23,
                1,
                """{"target":22,"rewardPlacement":"Inventory","rewards":[{"furni":"clothing_fungushead"},{"furni":"clothing_backkatana"},{"furni":"hween_c25_infectedplushie"}]}"""
            ),
            (
                "lt_r26_crackable",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"clothing_r26_spider","weight":32},{"furni":"clothing_r26_toucancompanion","weight":22},{"furni":"lt_r26_parasol","weight":18},{"furni":"lt_r26_fountain","weight":10},{"furni":"lt_r26_fan","weight":10},{"furni":"lt_r26_icecream","weight":8}]}"""
            ),
            (
                "mexico_c24_deluxepinata",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"clothing_floralguitar","also":["mexico_c24_minipumpkins","mexico_c24_festivedrinks","mexico_c24_meatballskewers","mexico_c24_paintedchair","mexico_c24_partytable"],"weight":26},{"furni":"clothing_skullguitar","also":["mexico_c24_tacoplate","mexico_c24_festiveflags","clothing_roseinmouth","mexico_c24_tabledecorations"],"weight":26},{"furni":"clothing_mustache","also":["clothing_acousticguitar","mexico_c24_pricklyplant","clothing_charmnecklace","clothing_fluffyearrings"],"weight":26},{"furni":"clothing_classicsombrero","also":["clothing_charmnecklace","mexico_c24_archway","mexico_c24_oaxacan"],"weight":12},{"furni":"clothing_vibrantguitar","also":["mexico_c24_pricklyplant","clothing_mariachioutfit","clothing_classicsombrero"],"weight":5},{"furni":"clothing_vibrantguitar","also":["clothing_traditionaldress","mexico_c24_archway","mexico_c24_oaxacan"],"weight":5}]}"""
            ),
            (
                "mexico_c24_pinata",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"mexico_c24_tacoplate","also":["mexico_c24_minipumpkins","mexico_c24_meatballskewers","mexico_c24_festiveflags","clothing_mustache"],"weight":26},{"furni":"mexico_c24_festivedrinks","also":["mexico_c24_tacoplate","mexico_c24_tabledecorations","mexico_c24_meatballskewers","clothing_fluffyearrings"],"weight":26},{"furni":"mexico_c24_tabledecorations","also":["mexico_c24_festivedrinks","mexico_c24_minipumpkins","mexico_c24_festiveflags","clothing_roseinmouth"],"weight":26},{"furni":"mexico_c24_partytable","also":["mexico_c24_paintedchair","mexico_c24_paintedchair","clothing_acousticguitar"],"weight":12},{"furni":"clothing_classicsombrero","also":["mexico_c24_partytable","mexico_c24_pricklyplant","clothing_floralguitar"],"weight":5},{"furni":"mexico_c24_paintedchair","also":["clothing_charmnecklace","clothing_skullguitar","mexico_c24_archway"],"weight":5}]}"""
            ),
            ("mini_c24_magnifyingglass1", 3, 1, """{"target":1,"rewardPlacement":"Inventory"}"""),
            ("mini_c24_magnifyingglass2", 3, 1, """{"target":1,"rewardPlacement":"Inventory"}"""),
            (
                "mushroom_c21_crackable",
                3,
                1,
                """{"target":1,"requiredEffectId":186,"rewards":[{"furni":"mushroom_c21_chair","weight":17},{"furni":"mushroom_c21_table","weight":15},{"furni":"mushroom_c21_bigmushroom","weight":13},{"furni":"mushroom_c21_bouncymushroom","weight":13},{"furni":"mushroom_c21_shelves","weight":11},{"furni":"mushroom_c21_drawers","weight":11},{"furni":"mushroom_c21_archway","weight":10},{"furni":"clothing_petalhat","weight":4},{"furni":"clothing_mushroom2","weight":4},{"furni":"clothing_flowerdress","weight":2}]}"""
            ),
            (
                "neopets_c25_crackableegg",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"neopets_c25_aisha1"},{"furni":"neopets_c25_aisha2"},{"furni":"neopets_c25_aisha3"},{"furni":"neopets_c25_kougra1"},{"furni":"neopets_c25_kougra2"},{"furni":"neopets_c25_kougra3"},{"furni":"neopets_c25_cybunny1"},{"furni":"neopets_c25_cybunny2"},{"furni":"neopets_c25_cybunny3"},{"furni":"neopets_c25_shoyru1"},{"furni":"neopets_c25_shoyru2"},{"furni":"neopets_c25_shoyru3"},{"furni":"neopets_c25_lupe1"},{"furni":"neopets_c25_lupe2"},{"furni":"neopets_c25_lupe3"},{"furni":"neopets_c25_eyrie1"},{"furni":"neopets_c25_eyrie2"},{"furni":"neopets_c25_eyrie3"}]}"""
            ),
            (
                "neopets_c25_crackablexmas",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"neopets_c25_aishaxmas"},{"furni":"neopets_c25_kougraxmas"},{"furni":"neopets_c25_cybunnyxmas"},{"furni":"neopets_c25_kacheekxmas"},{"furni":"neopets_c25_shoyruxmas"},{"furni":"neopets_c25_lupexmas"},{"furni":"neopets_c25_acaraxmas"},{"furni":"neopets_c25_draikxmas"},{"furni":"neopets_c25_eyriexmas"},{"furni":"neopets_c25_unixmas"},{"furni":"neopets_c25_xweetokxmas"},{"furni":"neopets_c25_brucexmas"}]}"""
            ),
            (
                "neopets_c26_crackableeaster",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"neopets_c26_kacheek1"},{"furni":"neopets_c26_kacheek2"},{"furni":"neopets_c26_kacheek3"},{"furni":"neopets_c26_acara1"},{"furni":"neopets_c26_acara2"},{"furni":"neopets_c26_acara3"},{"furni":"neopets_c26_uni1"},{"furni":"neopets_c26_uni2"},{"furni":"neopets_c26_uni3"},{"furni":"neopets_c26_draik1"},{"furni":"neopets_c26_draik2"},{"furni":"neopets_c26_draik3"},{"furni":"neopets_c26_xweetok1"},{"furni":"neopets_c26_xweetok2"},{"furni":"neopets_c26_xweetok3"},{"furni":"neopets_c26_bruce1"},{"furni":"neopets_c26_bruce2"},{"furni":"neopets_c26_bruce3"}]}"""
            ),
            (
                "neopets_c26_crackableval",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"neopets_c26_kacheekval"},{"furni":"neopets_c26_bruceval"},{"furni":"neopets_c26_unival"},{"furni":"neopets_c26_aishaval"},{"furni":"neopets_c26_cybunnyval"},{"furni":"neopets_c26_lupeval"},{"furni":"neopets_c26_draikval"},{"furni":"neopets_c26_kougraval"},{"furni":"neopets_c26_shoyruval"},{"furni":"neopets_c26_xweetokfae"},{"furni":"neopets_c26_acarafae"},{"furni":"neopets_c26_eyriefae"}]}"""
            ),
            (
                "ny_r21_crackable",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"clothing_r21_nystarhat1","weight":4},{"furni":"clothing_r21_nystarhat2","weight":12},{"furni":"clothing_r21_nystarhat3","weight":16},{"furni":"clothing_r21_nystarhat4","weight":16},{"furni":"clothing_r21_nystarhat5","weight":12},{"furni":"clothing_r21_nystarhat6","weight":12},{"furni":"clothing_r21_nystarhat7","weight":12},{"furni":"clothing_r21_nystarhat8","weight":16}]}"""
            ),
            (
                "ny_r22_crackable",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"clothing_r22_nypartyhorn1","weight":12},{"furni":"clothing_r22_nypartyhorn2","weight":16},{"furni":"clothing_r22_nypartyhorn3","weight":12},{"furni":"clothing_r22_nypartyhorn4","weight":12},{"furni":"clothing_r22_nypartyhorn5","weight":16},{"furni":"clothing_r22_nypartyhorn6","weight":16},{"furni":"clothing_r22_nypartyhorn7","weight":12},{"furni":"clothing_r22_nypartyhorn8","weight":4}]}"""
            ),
            (
                "ny_r23_crackable",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"clothing_r22_nytie1","weight":12},{"furni":"clothing_r22_nytie2","weight":16},{"furni":"clothing_r22_nytie3","weight":4},{"furni":"clothing_r22_nytie4","weight":16},{"furni":"clothing_r22_nytie5","weight":12},{"furni":"clothing_r22_nytie6","weight":16},{"furni":"clothing_r22_nytie7","weight":12},{"furni":"clothing_r22_nytie8","weight":12}]}"""
            ),
            (
                "ny_r24_crackable",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"clothing_r24_starboppers3","weight":4},{"furni":"clothing_r24_starboppers1","weight":12},{"furni":"clothing_r24_starboppers2","weight":12},{"furni":"clothing_r24_starboppers4","weight":12},{"furni":"clothing_r24_starboppers5","weight":16},{"furni":"clothing_r24_starboppers6","weight":12},{"furni":"clothing_r24_starboppers7","weight":16},{"furni":"clothing_r24_starboppers8","weight":16}]}"""
            ),
            (
                "ny_r25_crackable",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"clothing_r25_nystargarland1","weight":12},{"furni":"clothing_r25_nystargarland2","weight":12},{"furni":"clothing_r25_nystargarland3","weight":4},{"furni":"clothing_r25_nystargarland4","weight":12},{"furni":"clothing_r25_nystargarland5","weight":16},{"furni":"clothing_r25_nystargarland6","weight":12},{"furni":"clothing_r25_nystargarland7","weight":16},{"furni":"clothing_r25_nystargarland8","weight":16}]}"""
            ),
            (
                "nyc_c23_bag1",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"nyc_c23_fastfood","also":["nyc_c23_bagels","nyc_c23_breakfast"]},{"furni":"nyc_c23_fastfood","also":["nyc_c23_fastfood","nyc_c23_fastfood","nyc_c23_blueprints"]},{"furni":"nyc_c23_bagels","also":["nyc_c23_bagels","nyc_c23_bagels","nyc_c23_blueprints"]},{"furni":"nyc_c23_breakfast","also":["nyc_c23_breakfast","nyc_c23_breakfast","nyc_c23_blueprints"]},{"furni":"nyc_c23_fastfood","also":["nyc_c23_fastfood","nyc_c23_bagels"]},{"furni":"nyc_c23_bagels","also":["nyc_c23_bagels","nyc_c23_breakfast"]},{"furni":"nyc_c23_breakfast","also":["nyc_c23_breakfast","nyc_c23_fastfood"]},{"furni":"nyc_c23_fastfood","also":["nyc_c23_fastfood","nyc_c23_breakfast"]},{"furni":"nyc_c23_bagels","also":["nyc_c23_bagels","nyc_c23_fastfood"]},{"furni":"nyc_c23_breakfast","also":["nyc_c23_breakfast","nyc_c23_bagels"]}]}"""
            ),
            (
                "nyc_c23_bag2",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"nyc_c23_sandwich","also":["nyc_c23_donuts","nyc_c23_salad"]},{"furni":"nyc_c23_sandwich","also":["nyc_c23_sandwich","nyc_c23_sandwich"]},{"furni":"nyc_c23_donuts","also":["nyc_c23_donuts","nyc_c23_donuts"]},{"furni":"nyc_c23_salad","also":["nyc_c23_salad","nyc_c23_salad"]},{"furni":"nyc_c23_sandwich","also":["nyc_c23_sandwich","nyc_c23_donuts"]},{"furni":"nyc_c23_donuts","also":["nyc_c23_donuts","nyc_c23_salad"]},{"furni":"nyc_c23_salad","also":["nyc_c23_salad","nyc_c23_sandwich"]},{"furni":"nyc_c23_sandwich","also":["nyc_c23_sandwich","nyc_c23_salad"]},{"furni":"nyc_c23_donuts","also":["nyc_c23_donuts","nyc_c23_sandwich"]},{"furni":"nyc_c23_salad","also":["nyc_c23_salad","nyc_c23_donuts"]}]}"""
            ),
            (
                "olympus_c25_pandorasboxcrackable",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"olympus_c25_zeusalter"},{"furni":"olympus_c25_aphroditealter"},{"furni":"olympus_c25_dionysusalter"},{"furni":"olympus_c25_hadesalter"},{"furni":"clothing_olympiantoga"}]}"""
            ),
            (
                "pj_c26_pillowcrackable",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"pj_c26_nightlightcat","also":["pj_c26_nightlightbunny","pj_c26_boardgames","pj_c26_toothbrushes"],"weight":15},{"furni":"pj_c26_nightlightghost","also":["pj_c26_nightlightbunny","pj_c26_boardgames","pj_c26_frankplush"],"weight":15},{"furni":"pj_c26_nightlightghost","also":["pj_c26_toothbrushes","pj_c26_duckplush","pj_c26_frankplush"],"weight":15},{"furni":"pj_c26_nightlightcat","also":["pj_c26_duckplush","clothing_borrowedshirt3"],"weight":10},{"furni":"pj_c26_nightlightbunny","also":["pj_c26_toothbrushes","clothing_borrowedshirt2"],"weight":10},{"furni":"pj_c26_nightlightghost","also":["pj_c26_boardgames","clothing_borrowedshirt1"],"weight":10},{"furni":"pj_c26_nightlightduck","also":["pj_c26_sleepytimeduck","clothing_bedroll"],"weight":10},{"furni":"pj_c26_nightlightcat","also":["pj_c26_pillowdragon","clothing_sleepytimebun"],"weight":5},{"furni":"pj_c26_nightlightduck","also":["pj_c26_duckplush","clothing_sharkonesie"],"weight":5},{"furni":"pj_c26_sleepytimeduck","also":["pj_c26_frankplush","clothing_sleepytimeadonis"],"weight":5}]}"""
            ),
            (
                "rainbow_c21_crackable1",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"rainbow_c19_lights","weight":18},{"furni":"rainbow_c19_chair","weight":18},{"furni":"rainbow_c19_rug","weight":16},{"furni":"rainbow_c19_table","weight":16},{"furni":"rainbow_c19_flags","weight":15},{"furni":"rainbow_c19_bed","weight":12},{"furni":"rainbow_c21_crackable2","weight":5}]}"""
            ),
            (
                "rainbow_c21_crackable2",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"rainbow_c21_lightbulbheart","weight":225},{"furni":"rainbow_c21_balloonarch","weight":225},{"furni":"rainbow_c21_rainbowroad","weight":225},{"furni":"rainbow_c21_bunting","weight":225},{"furni":"clothing_pridecape","weight":25},{"furni":"clothing_pridehoodie","weight":25},{"furni":"clothing_rainbowwings","weight":25},{"furni":"clothing_rainbowundercut","weight":25}]}"""
            ),
            (
                "school_c22_crackable",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"school_c22_paintings","also":["school_c22_arttable"],"weight":32},{"furni":"school_c22_equipment","also":["school_c22_duffelbag"],"weight":32},{"furni":"school_c22_cello","also":["school_c22_xylophone"],"weight":32},{"furni":"clothing_schoolblazer","weight":4}]}"""
            ),
            (
                "skorea_c22_idolbox",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"skorea_c22_makeup1","also":["skorea_c22_photocard3","skorea_c22_vinyl2"],"weight":14},{"furni":"skorea_c22_makeup2","also":["skorea_c22_photocard2","skorea_c22_vinyl3"],"weight":14},{"furni":"skorea_c22_makeup3","also":["skorea_c22_photocard1","skorea_c22_vinyl1"],"weight":14},{"furni":"skorea_c22_makeup1","also":["skorea_c22_photocard2","skorea_c22_vinyl1"],"weight":14},{"furni":"skorea_c22_makeup2","also":["skorea_c22_photocard1","skorea_c22_vinyl2"],"weight":14},{"furni":"skorea_c22_makeup3","also":["skorea_c22_photocard3","skorea_c22_vinyl3"],"weight":14},{"furni":"skorea_c22_makeup1","also":["skorea_c22_photocard3","skorea_c22_vinyl2","clothing_idolhairlong"],"weight":2},{"furni":"skorea_c22_makeup2","also":["skorea_c22_photocard2","skorea_c22_vinyl3","clothing_glittertop"],"weight":3},{"furni":"skorea_c22_makeup3","also":["skorea_c22_photocard1","skorea_c22_vinyl1","clothing_cutepunkskirt"],"weight":3},{"furni":"skorea_c22_makeup1","also":["skorea_c22_photocard2","skorea_c22_vinyl1","clothing_idolhairlong"],"weight":2},{"furni":"skorea_c22_makeup2","also":["skorea_c22_photocard1","skorea_c22_vinyl2","clothing_glittertop"],"weight":3},{"furni":"skorea_c22_makeup3","also":["skorea_c22_photocard3","skorea_c22_vinyl3","clothing_cutepunkskirt"],"weight":3}]}"""
            ),
            (
                "skorea_c22_idolbox2",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"skorea_c22_lightstick1","also":["skorea_c22_photocard6","skorea_c22_vinyl5"],"weight":14},{"furni":"skorea_c22_lightstick3","also":["skorea_c22_photocard4","skorea_c22_vinyl6"],"weight":14},{"furni":"skorea_c22_lightstick2","also":["skorea_c22_photocard5","skorea_c22_vinyl4"],"weight":14},{"furni":"skorea_c22_lightstick1","also":["skorea_c22_photocard4","skorea_c22_vinyl4"],"weight":14},{"furni":"skorea_c22_lightstick3","also":["skorea_c22_photocard5","skorea_c22_vinyl5"],"weight":14},{"furni":"skorea_c22_lightstick2","also":["skorea_c22_photocard6","skorea_c22_vinyl6"],"weight":14},{"furni":"skorea_c22_lightstick1","also":["skorea_c22_photocard6","skorea_c22_vinyl5","clothing_2layeredshirt"],"weight":3},{"furni":"skorea_c22_lightstick3","also":["skorea_c22_photocard4","skorea_c22_vinyl6","clothing_idolhairshort"],"weight":2},{"furni":"skorea_c22_lightstick2","also":["skorea_c22_photocard5","skorea_c22_vinyl4","clothing_grungetrousers"],"weight":3},{"furni":"skorea_c22_lightstick1","also":["skorea_c22_photocard4","skorea_c22_vinyl4","clothing_idolhairshort"],"weight":2},{"furni":"skorea_c22_lightstick3","also":["skorea_c22_photocard5","skorea_c22_vinyl5","clothing_2layeredshirt"],"weight":3},{"furni":"skorea_c22_lightstick2","also":["skorea_c22_photocard6","skorea_c22_vinyl6","clothing_grungetrousers"],"weight":3}]}"""
            ),
            (
                "spa_c20_crackable1A",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"spa_c20_bbmint","also":["spa_c20_bbcharcoal","spa_c20_bbcharcoal","clothing_eyecitrus","spa_c20_lavendersalt","clothing_towelhair","clothing_towelwrapfull"]},{"furni":"spa_c20_bbcharcoal","also":["spa_c20_bbmint","spa_c20_bbmint","clothing_eyestrawberry","spa_c20_incense","clothing_eyemask","clothing_towelwrapfull"]}]}"""
            ),
            (
                "spa_c20_crackable2A",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"spa_c20_bbrose","also":["spa_c20_bbcitrus","spa_c20_bbcitrus","clothing_eyecucumber","spa_c20_lavendersalt","clothing_towelhair","clothing_towelwraphalf"]},{"furni":"spa_c20_bbcitrus","also":["spa_c20_bbrose","spa_c20_bbrose","clothing_eyetomato","spa_c20_incense","clothing_eyemask","clothing_towelwraphalf"]}]}"""
            ),
            (
                "stellar_c23_starcage",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"stellar_c23_aries","also":["stellar_c23_taurus","stellar_c23_gemini"]},{"furni":"stellar_c23_cancer","also":["stellar_c23_leo","stellar_c23_virgo"]},{"furni":"stellar_c23_libra","also":["stellar_c23_scorpio","stellar_c23_sagittarius"]},{"furni":"stellar_c23_capricorn","also":["stellar_c23_aquarius","stellar_c23_pisces"]},{"furni":"stellar_c23_aries","also":["stellar_c23_cancer","stellar_c23_libra"]},{"furni":"stellar_c23_taurus","also":["stellar_c23_scorpio","stellar_c23_aquarius"]},{"furni":"stellar_c23_virgo","also":["stellar_c23_sagittarius","stellar_c23_pisces"]}]}"""
            ),
            (
                "thai_c21_woodcarvingset",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"thai_c21_woodenendtable","weight":24},{"furni":"thai_c21_woodensofa","weight":24},{"furni":"thai_c21_woodenstatue","weight":24},{"furni":"thai_c21_woodenwardrobe","weight":24},{"furni":"thai_r21_clothingbox","weight":4}]}"""
            ),
            (
                "thai_r21_clothingbox",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"clothing_thaibunhair","weight":25},{"furni":"clothing_thaihat","weight":25},{"furni":"clothing_thaidress","weight":25},{"furni":"clothing_thaisuit","weight":25}]}"""
            ),
            ("val_c22_brokenvan", 3, 1, """{"target":1}"""),
            (
                "wonderland_c25_crackable",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"wonderland_c25_spadecard","also":["wonderland_c25_spadecard","wonderland_c25_drinkme"],"weight":330},{"furni":"wonderland_c25_clubcard","also":["wonderland_c25_clubcard","wonderland_c25_teacup"],"weight":330},{"furni":"wonderland_c25_spadecard","also":["wonderland_c25_spadecard","wonderland_c25_clubcard"],"weight":165},{"furni":"wonderland_c25_clubcard","also":["wonderland_c25_clubcard","wonderland_c25_spadecard"],"weight":165}]}"""
            ),
            (
                "wonderland_c25_redcrackable",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"wonderland_c25_heartcard","also":["wonderland_c25_heartcard","wonderland_c25_eatme"],"weight":330},{"furni":"wonderland_c25_diamondcard","also":["wonderland_c25_diamondcard","wonderland_c25_teapot"],"weight":330},{"furni":"wonderland_c25_heartcard","also":["wonderland_c25_heartcard","wonderland_c25_diamondcard"],"weight":165},{"furni":"wonderland_c25_diamondcard","also":["wonderland_c25_diamondcard","wonderland_c25_heartcard"],"weight":165}]}"""
            ),
            (
                "xmas_c21_crackableletter",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"xmas_c21_lockpick","also":["xmas_c21_key5","xmas_c21_map1"]},{"furni":"xmas_c21_lockpick","also":["xmas_c21_key5","xmas_c21_map2"]},{"furni":"xmas_c21_lockpick","also":["xmas_c21_key4","xmas_c21_map3"]},{"furni":"xmas_c21_lockpick","also":["xmas_c21_key4","xmas_c21_map4"]},{"furni":"xmas_c21_lockpick","also":["xmas_c21_key2","xmas_c21_map5"]},{"furni":"xmas_c21_lockpick","also":["xmas_c21_key2","xmas_c21_map6"]}]}"""
            ),
            (
                "xmas_c22_present1",
                21,
                2,
                """{"target":20,"rewardTo":"Cracker","rewards":[{"furni":"xmas_c22_ornament4"},{"furni":"xmas_c22_ornament3"},{"furni":"xmas_c22_ornament1"},{"furni":"xmas_c22_ornament2"}]}"""
            ),
            (
                "xmas_c22_present2",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"xmas_c22_ornament3","also":["xmas_c22_ornament4","xmas_c22_candycanes","xmas_c22_wrappingpaper"]},{"furni":"xmas_c22_ornament4","also":["xmas_c22_ornament4","xmas_c22_ornament4","xmas_c22_candycanes"]},{"furni":"xmas_c22_ornament3","also":["xmas_c22_ornament3","xmas_c22_ornament3","xmas_c22_wrappingpaper"]},{"furni":"xmas_c22_ornament3","also":["xmas_c22_ornament3","xmas_c22_ornament4","xmas_c22_ornament4"]},{"furni":"xmas_c22_wrappingpaper","also":["xmas_c22_wrappingpaper","xmas_c22_wrappingpaper","xmas_c22_candycanes"]},{"furni":"xmas_c22_candycanes","also":["xmas_c22_candycanes","xmas_c22_candycanes","xmas_c22_wrappingpaper"]},{"furni":"xmas_c22_ornament4","also":["xmas_c22_ornament4","xmas_c22_ornament4","xmas_c22_wrappingpaper"]},{"furni":"xmas_c22_ornament3","also":["xmas_c22_ornament3","xmas_c22_ornament3","xmas_c22_candycanes"]}]}"""
            ),
            (
                "xmas_c23_crackable1",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"xmas_c23_eggs","also":["xmas_c23_milkpowder","xmas_c23_cakemix"],"weight":165},{"furni":"xmas_c23_sugar","also":["xmas_c23_cocao","xmas_c23_eggs"],"weight":165},{"furni":"xmas_c23_cocao","also":["xmas_c23_eggs","xmas_c23_milkpowder"],"weight":165},{"furni":"xmas_c23_milkpowder","also":["xmas_c23_cakemix","xmas_c23_water"],"weight":165},{"furni":"xmas_c23_cakemix","also":["xmas_c23_water","xmas_c23_sugar"],"weight":165},{"furni":"xmas_c23_sugar","also":["xmas_c23_cocao","xmas_c23_water"],"weight":165},{"furni":"xmas_c23_goldenticket","weight":10}]}"""
            ),
            (
                "xmas_c23_crackable2",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"xmas_c23_chocolatebar","also":["xmas_c23_berryfruits","xmas_c23_mint"],"weight":158},{"furni":"xmas_c23_sprinkles","also":["xmas_c23_sprinkles","xmas_c23_chocolatebar"],"weight":158},{"furni":"xmas_c23_chocolatebar","also":["xmas_c23_chocolatebar","xmas_c23_berryfruits"],"weight":158},{"furni":"xmas_c23_berryfruits","also":["xmas_c23_berryfruits","xmas_c23_mint"],"weight":158},{"furni":"xmas_c23_mint","also":["xmas_c23_mint","xmas_c23_sprinkles"],"weight":158},{"furni":"xmas_c23_sprinkles","also":["xmas_c23_berryfruits","xmas_c23_mint"],"weight":158},{"furni":"xmas_c23_goldenticket","weight":50}]}"""
            ),
            (
                "xmas_c24_crackable1",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"xmas_c24_hungryducks"},{"furni":"xmas_c24_ducktrapgame"},{"furni":"xmas_c24_kickeroo"},{"furni":"xmas_c24_crackable2"}]}"""
            ),
            (
                "xmas_c24_crackable2",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"xmas_c24_patchbaby"},{"furni":"xmas_c24_retroconsole"},{"furni":"xmas_c24_drawpad"},{"furni":"xmas_c24_crackable3"}]}"""
            ),
            (
                "xmas_c24_crackable3",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"xmas_c24_pogoball"},{"furni":"xmas_c24_mrfrankhead"},{"furni":"xmas_c24_bonniepocket"},{"furni":"xmas_c24_crackable4"}]}"""
            ),
            (
                "xmas_c24_crackable4",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"clothing_hollydress"},{"furni":"clothing_dressinggown"}]}"""
            ),
            (
                "xmas_c25_treedecorcrackable",
                3,
                1,
                """{"target":1,"rewardPlacement":"Inventory","rewards":[{"furni":"xmas_c25_treebaubles","also":["xmas_c25_treelights","xmas_c25_treelights"]},{"furni":"xmas_c25_treetinsel","also":["xmas_c25_treebaubles","xmas_c25_treebaubles"]},{"furni":"xmas_c25_treesnowflake","also":["xmas_c25_treetinsel","xmas_c25_treetinsel"]},{"furni":"xmas_c25_treecandycane","also":["xmas_c25_treesnowflake","xmas_c25_treesnowflake"]},{"furni":"xmas_c25_treelights","also":["xmas_c25_treecandycane","xmas_c25_treecandycane"]}]}"""
            ),
            (
                "xmas_r25_habububox",
                3,
                1,
                """{"target":1,"rewards":[{"furni":"xmas_r25_habubulove","weight":16},{"furni":"xmas_r25_habubufun","weight":14},{"furni":"xmas_r25_habubucosy","weight":13},{"furni":"xmas_r25_habubuhappiness","weight":12},{"furni":"xmas_r25_habubucalm","weight":11},{"furni":"xmas_r25_habubuhope","weight":10},{"furni":"xmas_r25_habubudream","weight":10},{"furni":"xmas_r25_habubuluck","weight":9},{"furni":"xmas_r25_habubuglam","also":["clothing_r25_habubuglam"],"weight":5}]}"""
            ),
        ];

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            foreach (var (name, states, usage, crackable) in CRACKABLES)
                migrationBuilder.Sql(
                    $"UPDATE `furniture_definitions` SET `logic` = '{LOGIC}', `total_states` = {states}, `usage_policy` = {usage}, "
                        + $"`extra_data` = IF(JSON_VALID(`extra_data`), JSON_SET(`extra_data`, '$.crackable', JSON_EXTRACT('{crackable}', '$')), "
                        + $"JSON_OBJECT('crackable', JSON_EXTRACT('{crackable}', '$'))) "
                        + $"WHERE `name` = '{name}' AND `logic` IN ('default_floor', 'none', '', '{LOGIC}');"
                );
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            foreach (var (name, _, _, _) in CRACKABLES)
                migrationBuilder.Sql(
                    "UPDATE `furniture_definitions` SET `logic` = 'default_floor', `extra_data` = "
                        + "IF(JSON_VALID(`extra_data`) AND JSON_LENGTH(JSON_REMOVE(`extra_data`, '$.crackable')) > 0, JSON_REMOVE(`extra_data`, '$.crackable'), "
                        + $"IF(JSON_VALID(`extra_data`), NULL, `extra_data`)) WHERE `name` = '{name}' AND `logic` = '{LOGIC}';"
                );
        }
    }
}
