<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Turbo.Contracts\Turbo.Contracts.csproj" />
    <ProjectReference Include="..\Turbo.Database\Turbo.Database.csproj" />
    <ProjectReference Include="..\Turbo.Primitives\Turbo.Primitives.csproj" />
  </ItemGroup>
</Project>
