namespace Turbo.Primitives.Rooms.Enums.Wired;

public enum WiredTriggerType
{
    AVATAR_SAYS_SOMETHING = 0,
    AVATAR_WALKS_ON_FURNI = 1,
    AVATAR_WALKS_OFF_FURNI = 2,
    TRIGGER_ONCE = 3,
    USE_STUFF = 4,
    TRIGGER_PERIODICALLY = 6,
    AVATAR_ENTERS_ROOM = 7,
    GAME_STARTS = 8,
    GAME_ENDS = 9,
    SCORE_ACHIEVED = 10,
    AVATAR_CAUGHT = 11,
    PERIODIC_LONG = 12,
    BOT_DESTINATION_REACHED = 13,
    BOT_AVATAR_REACHED = 14,
    CLOCK_REACH_TIME = 15,
    AVATAR_PERFORMS_ACTION = 16,
    RECEIVE_SIGNAL = 17,
    AVATAR_CLICKS_FURNI = 18,
    PERIODIC_SHORT = 19,
    STATE_CHANGE = 20,
    USER_CLICKS_TILE = 21,
    VARIABLE_UPDATE = 22,
    AVATAR_LEAVES_ROOM = 23,
    AVATAR_CLICKS_AVATAR = 24,
}
