namespace Turbo.Primitives.Rooms.Enums.Wired;

public enum WiredAddonType
{
    CONDITION_EVALUATION = 0,
    RANDOM_ACTION = 1,
    INEDITED_ACTION = 2,
    EXECUTION_LIMIT = 5,
    NO_MOVE_ANIMATION = 6,
    MOVE_PHYSICS = 7,
    CARRY_USERS = 8,
    ANIMATION_TIME = 9,
    FURNI_SELECTOR_FILTER = 10,
    USER_SELECTOR_FILTER = 11,
    FURNI_VARIABLE_FILTER = 12,
    USER_VARIABLE_FILTER = 13,
    USERNAME_PLACEHOLDER = 14,
    VARIABLE_PLACEHOLDER = 15,
    VARIABLE_CAPTURER = 16,
    EXECUTE_IN_ORDER = 17,
    VARIABLE_TEXT_CONVERTER = 1000,
}
